from mod11_check import mod11_check
from nhs_number_format_check import nhs_number_format_check
from palindromic_nhs_number_check import palindromic_nhs_number_check
from sensitive_legally_restricted import sensitive_legally_restricted