class EventTiming:
    """
    List of valid event timing codes. Validations have been taken from the
    following sources:
        Event Timing -  https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/83110/~overview
        Timing Event - https://simplifier.net/packages/hl7.fhir.r4.core/4.0.1/files/81021
    """

    VALID_EVENT_TIMING_CODES = [
        "MORN",
        "MORN.early",
        "MORN.late",
        "NOON",
        "AFT",
        "AFT.early",
        "AFT.late",
        "EVE",
        "EVE.early",
        "EVE.late",
        "NIGHT",
        "PHS",
    ]
    VALID_TIMING_EVENT_CODES = [
        "AC",
        "ACD",
        "ACM",
        "ACV",
        "C",
        "CD",
        "CM",
        "CV",
        "HS",
        "IC",
        "ICD",
        "ICM",
        "ICV",
        "PC",
        "PCD",
        "PCM",
        "PCV",
        "WAKE"
    ]


class DosageUnits:
    """
    List of valid, commonly used dosage units. As above, taken from:
            https://www.hl7.org/fhir/valueset-UCUM-common.xml
    """

    VALID_UNIT_CODES = [
        "%",
        "%/100{WBC}",
        "%{0to3Hours}",
        "%{Abnormal}",
        "%{Activity}",
        "%{BasalActivity}",
        "%{Binding}",
        "%{Blockade}",
        "%{Carboxyhemoglobin}",
        "%{Conversion}",
        "%{Cound}",
        "%{EosSeen}",
        "%{Excretion}",
        "%{Fat}",
        "%{FetalErythrocytes}",
        "%{Hemoglobin}",
        "%{HemoglobinA1C}",
        "%{HemoglobinSaturation}",
        "%{Hemolysis}",
        "%{HumanResponse}",
        "%{Index}",
        "%{Inhibition}",
        "%{Live}",
        "%{Negative Control}",
        "%{Normal}",
        "%{NormalControl}",
        "%{NormalPooledPlasma}",
        "%{ofAvailable}",
        "%{ofBacteria}",
        "%{OfLymphocytes}",
        "%{OfWBCs}",
        "%{Oxygen}",
        "%{Positive}",
        "%{Precipitate}",
        "%{Reactivity}",
        "%{response}",
        "%{risk}",
        "%{SpermMotility}",
        "%{Total}",
        "%{TotalProtein}",
        "%{Tot'Cholesterol}",
        "%{Tot'Hgb}",
        "%{Uptake}",
        "%{vol}",
        "%{WeightToWeight}",
        "/(12.h)",
        "/[arb'U]",
        "/[HPF]",
        "/[iU]",
        "/[LPF]",
        "/{Entity}",
        "/[HPF]",
        "/[LPF]",
        "/{oif}",
        "/{Specimen}",
        "/{tot}",
        "/10*10",
        "/10*12",
        "/10*12{rbc}",
        "/10*6",
        "/10*9",
        "/100",
        "/100{cells}",
        "/100{neutrophils}",
        "/100{spermatozoa}",
        "/100{WBC}",
        "/100{WBCs}",
        "/a",
        "/cm[H2O]",
        "/d",
        "/dL",
        "/g",
        "/g{creat}",
        "/g{hgb}",
        "/g{tot'nit}",
        "/g{tot'prot}",
        "/g{wet'tis}",
        "/h",
        "/kg",
        "/kg{body'wt}",
        "/L",
        "/m2",
        "/mg",
        "/min",
        "/mL",
        "/mm3",
        "/mmol",
        "/mo",
        "/s",
        "/U",
        "/ug",
        "/uL",
        "/wk",
        "[APL'U]",
        "[APL'U]/mL",
        "[arb'U]",
        "[arb'U]/L",
        "[arb'U]/mL",
        "[AU]",
        "[BAU]",
        "[beth'U]",
        "[beth'U]",
        "[CFU]",
        "[CFU]/L",
        "[CFU]/mL",
        "[Ch]",
        "[cin_i]",
        "[cup_us]",
        "[degF]",
        "[dr_av]",
        "[drp]",
        "[drp]/[HPF]",
        "[drp]/h",
        "[drp]/min",
        "[drp]/mL",
        "[drp]/s",
        "[fdr_us]",
        "[foz_br]",
        "[foz_us]",
        "[ft_i]",
        "[fth_i]",
        "[gal_br]",
        "[gal_us]",
        "[GPL'U]",
        "[gr]",
        "[in_i]",
        "[iU]",
        "[IU]/(2.h)",
        "[IU]/(24.h)",
        "[IU]/10*9{RBCs}",
        "[IU]/d",
        "[IU]/dL",
        "[IU]/g",
        "[IU]/g{Hb}",
        "[iU]/g{Hgb}",
        "[IU]/h",
        "[IU]/kg",
        "[IU]/kg/d",
        "[IU]/L",
        "[IU]/min",
        "[IU]/mL",
        "[lb_av]",
        "[mi_i]",
        "[mi_us]",
        "[min_us]",
        "[MPL'U]",
        "[nmi_i]",
        "[oz_av]",
        "[oz_tr]",
        "[pH]",
        "[pi].rad/min",
        "[ppb]",
        "[ppm]",
        "[ppm]{v/v}",
        "[pptr]",
        "[ppth]",
        "[pptr]",
        "[psi]",
        "[pt_br]",
        "[qt_br]",
        "[qt_us]",
        "[sft_i]",
        "[sin_i]",
        "[ston_av]",
        "[syd_i]",
        "[tbs_us]",
        "[tb'U]",
        "[todd'U]",
        "[todd'U]",
        "[tsp_us]",
        "[yd_i]",
        "{# of calculi}",
        "{# of donor informative markers}",
        "{# of fetuses}",
        "{# of informative markers}",
        "{#}",
        "{2 or 3 times}/d",
        "{3 times}/d",
        "{4 times}/d",
        "{5 times}/d",
        "{absorbance}",
        "{Absorbance'U}",
        "{Absorbance'U}/mL",
        "{activity}",
        "{ActivityCoefficient}",
        "{AHF'U}",
        "{AntibodyResponse'U}",
        "{Applicator}",
        "{APS'U}",
        "{AspirinReaction'U}",
        "{Bead}",
        "{Beats}/min",
        "{Bottle}",
        "{Bowls}/d",
        "{Breaths}/min",
        "{CAE'U}",
        "{CagRepeat}",
        "{Can}",
        "{Cans}/wk",
        "{Capsule}",
        "{Cell}",
        "{cells}",
        "{cells}/[HPF]",
        "{Cells}/mL",
        "{cells}/uL",
        "{CfTiter}",
        "{cfu}",
        "{cfu}/mL",
        "{CGG_repeats}",
        "{CGG}",
        "{CH100'U}",
        "{clock time}",
        "{clock_time}",
        "{ComplementActivityEnzyme'U}",
        "{ComplementCH100'U}",
        "{ComplementCH50'U}",
        "{copies}/mL",
        "{copies}/ug",
        "{Copies}/uL",
        "{Count}",
        "{Counts}/min",
        "{Dalton}",
        "{DdTiter}",
        "{DeltaOpticalDensity}",
        "{Dilution}",
        "{Disintegrations}/min",
        "{Dose}",
        "{Drinks}/d",
        "{Each}",
        "{Ehrlich'U}",
        "{Ehrlich'U}/(2.h)",
        "{Ehrlich'U}/100.g",
        "{Ehrlich'U}/d",
        "{Ehrlich'U}/dL",
        "{Ehrlich'U}/mL",
        "{EIAIndex}",
        "{EIATiter}",
        "{EIA'U}",
        "{EIA'U}/U",
        "{ElisaIndex}",
        "{ELISA'U}",
        "{Elisa'U}/mL",
        "{ElisaValue}",
        "{ERY}/uL",
        "{Events}",
        "{FluorescenceIntensity'U}",
        "U{G}",
        "{GliadinIndexValue}",
        "{G-PortionPhospholipids}",
        "{HaTiter}",
        "{IfaIndex}",
        "{IfaTiter}",
        "{IgAAntiphosphatidyleserine'U}",
        "{IgAPhospholipid'U}",
        "{IgGAntiphosphatidyleserine'U}",
        "{IgGIndex}",
        "{IgMAntiphosphatidyleserine'U}",
        "{IgMIndex}",
        "{ImmuneComplex'U}",
        "{ImmuneStatusRatio}",
        "{Immunity}",
        "{Index_val}",
        "{index}",
        "{IndexValue}",
        "{InhaledTobaccoUseAmountYears}",
        "{InhaledTobaccoUsePacks}/d",
        "{INR}",
        "{INR'unit}",
        "{JDF'U}",
        "{JDF'U}/L",
        "{JuvenileDiabetesFound'U}",
        "{KCT'U}",
        "{KRONU'U}/L",
        "{KRONU'U}/mL",
        "{lgCopies}/ml",
        "{log_copies}/mL",
        "{log_IU}/mL",
        "{LymeIndexValue}",
        "{M.o.M.}",
        "{M.o.M}",
        "{Markers}",
        "{minidrp}",
        "{Molecule}/{Platelet}",
        "{M-PortionPhospholipids}",
        "{MPS'U}",
        "{MPS'U}/mL",
        "{MultOfMean}",
        "{NonspecificOunce}",
        "{Number}",
        "{OD_unit}",
        "{Once}/d",
        "{OpticalDensity}",
        "{OpticalDensityIndex}",
        "{OpticalDensityRatio}",
        "{P2Y12 Reaction Units}",
        "{Package}",
        "{Packs}/d",
        "{PackYears}",
        "{Patch}",
        "{Percentile}",
        "{Pill}",
        "{Pouches}/wk",
        "{RadioactiveT3UptakeRatio}",
        "{ratio}",
        "{RBC}/uL",
        "{RecTiter}",
        "{Relative'U}",
        "{RelativeViscosity}",
        "{RPI'U}",
        "{RubellaVirus}",
        "{SatIndex}",
        "{Scoop}",
        "{ScoreOf}",
        "{shift}",
        "{spermatozoa}/mL",
        "{spray}",
        "{StandardDeviation}",
        "{StandardIgA'U}",
        "{StandardIgG'U}",
        "{StandardIgM'U}",
        "{StdDeviation'U}",
        "{StimulatingIndex}",
        "{Streptozyme'U}",
        "{ThyroxinUptake'U}",
        "{TIBC'U}",
        "{Times}/wk",
        "{Tine'U}",
        "{titer}",
        "{ToxoplasmaIndexValue}",
        "{Vial}",
        "{Volume}/{Vvolume}",
        "{WeeksDays}",
        "{WhiteBloodCell}",
        "1/d",
        "1/min",
        "10*12/L",
        "10*3",
        "10*3.{RBC}",
        "10*3.U",
        "10*3/L",
        "10*3/mL",
        "10*3/uL",
        "10*3{Copies}/mL",
        "10*-3{Polarization'U}",
        "10*5",
        "10*6",
        "10*6.[iU]",
        "10*6.eq/mL",
        "10*6.U",
        "10*6/{Specimen}",
        "10*6/kg",
        "10*6/L",
        "10*6/mL",
        "10*6/mm3",
        "10*6/uL",
        "10*-6{Immunofluorescence'U}",
        "10*8",
        "10*9/L",
        "10*9/mL",
        "10*9/uL",
        "10.L/(min.m2)",
        "10.L/min",
        "10.uN.s/(cm.m2)",
        "10.uN.s/cm",
        "10.uN.s/cm2",
        "a",
        "A/m",
        "att",
        "bar",
        "Cel",
        "cg",
        "cL",
        "cm",
        "cm[H2O]",
        "cm[H2O]/(s.m)",
        "cm[H2O]/L/s",
        "cm[Hg]",
        "cm2",
        "cm2/s",
        "cm3",
        "cP",
        "cSt",
        "d",
        "dB",
        "deg",
        "deg/s",
        "dg",
        "dL",
        "dm",
        "dm2/s2",
        "eq",
        "eq/L",
        "eq/mL",
        "eq/mmol",
        "eq/umol",
        "erg",
        "eV",
        "fg",
        "fL",
        "fL/nL",
        "fm",
        "fmol",
        "fmol/g",
        "fmol/L",
        "fmol/mg",
        "fmol/mL",
        "g",
        "g.m",
        "g.m/({hb}.m2)",
        "g.m/{hb}",
        "g/(100.g)",
        "g/(12.h)",
        "g/(24.h)",
        "g/(3.d)",
        "g/(4.h)",
        "g/(48.h)",
        "g/(5.h)",
        "g/(6.h)",
        "g/(72.h)",
        "g/(8.h)",
        "g/(8.kg.h)",
        "g/(kg.h)",
        "g/(kg.min)",
        "g/{TotalWeight}",
        "g/d",
        "g/dL",
        "g/g",
        "g/g{Cre}",
        "g/g{creat}",
        "g/g{tissue}",
        "g/h",
        "g/h/m2",
        "g/kg",
        "g/kg/d",
        "g/L",
        "g/m2",
        "g/mg",
        "g/min",
        "g/mL",
        "g/mmol",
        "g/mmol{creat}",
        "g/mol",
        "GBq",
        "h",
        "hL",
        "Hz",
        "[iU]",
        "J",
        "J/L",
        "K",
        "K/W",
        "k[IU]/L",
        "k[IU]/mL",
        "kat/kg",
        "kat/L",
        "kBq",
        "kcal",
        "kcal/(8.h)",
        "kcal/h",
        "kg",
        "kg.m/s",
        "kg/(s.m2)",
        "kg/h",
        "kg/L",
        "kg/m2",
        "kg/m3",
        "kg/min",
        "kg/mol",
        "kg/s",
        "kL",
        "km",
        "kPa",
        "ks",
        "kU/g",
        "kU/h",
        "kU/L",
        "kU/mL",
        "L",
        "L.s2/s",
        "L/(8.h)",
        "L/(min.m2)",
        "L/d",
        "L/h",
        "L/kg",
        "L/L",
        "L/min",
        "L/s",
        "lm/m2",
        "m",
        "m/s",
        "m/s2",
        "m[iU]",
        "m[IU]/L",
        "m[IU]/mL",
        "m2",
        "m2/s",
        "m3/s",
        "mA",
        "mbar",
        "mbar.s/L",
        "MBq",
        "mCi",
        "meq",
        "meq/(12.h)",
        "meq/(2.h)",
        "meq/(24.h)",
        "meq/(8.h)",
        "meq/(8.h.kg)",
        "meq/(kg.d)",
        "meq/{Specimen}",
        "meq/d",
        "meq/dL",
        "meq/g",
        "meq/g{Cre}",
        "meq/h",
        "meq/kg",
        "meq/kg/h",
        "meq/kg/min",
        "meq/L",
        "meq/m2",
        "meq/min",
        "meq/mL",
        "mg",
        "mg/(10.h)",
        "mg/(12.h)",
        "mg/(18.h)",
        "mg/(2.h)",
        "mg/(24.h)",
        "mg/(72.h)",
        "mg/(8.h)",
        "mg/(8.h.kg)",
        "mg/(kg.h)",
        "mg/{Hgb}/g",
        "mg/{Specimen}",
        "mg/{Tot'Volume}",
        "mg/{Volume}",
        "mg/d",
        "mg/d/(173.10*-2.m2)",
        "mg/dL",
        "mg/g",
        "mg/g{Cre}",
        "mg/g{creat}",
        "mg/h",
        "mg/kg",
        "mg/kg/(24.h)",
        "mg/kg/d",
        "mg/kg/min",
        "mg/L",
        "mg/m2",
        "mg/m3",
        "mg/mg",
        "mg/mg{cre}",
        "mg/min",
        "mg/mL",
        "mg/mmol",
        "mg/mmol{Cre}",
        "mg/mmol{creat}",
        "mg/wk",
        "mg{Phenylketones}/dL",
        "min",
        "mL",
        "mL/({h'b}.m2)",
        "mL/(10.h)",
        "mL/(12.h)",
        "mL/(2.h)",
        "mL/(24.h)",
        "mL/(4.h)",
        "mL/(72.h)",
        "mL/(8.h)",
        "mL/(kg.min)",
        "mL/[sin_i]",
        "mL/{h'b}",
        "mL/cm[H2O]",
        "mL/d",
        "mL/dL",
        "mL/h",
        "mL/kg",
        "mL/kg/(8.h)",
        "mL/kg/d",
        "mL/kg/h",
        "mL/kg/min",
        "mL/L",
        "mL/m2",
        "mL/mbar",
        "mL/min",
        "mL/min/(173.10*-2.m2)",
        "mL/min/{1.73_m2}",
        "mL/min/m2",
        "mL/mm",
        "mL/s",
        "mm",
        "mm/h",
        "mm/min",
        "mm[H2O]",
        "mm[Hg]",
        "mm2",
        "mm3",
        "mmol",
        "mmol/(12.h)",
        "mmol/(18.h)",
        "mmol/(2.h)",
        "mmol/(24.h)",
        "mmol/(6.h)",
        "mmol/(8.h)",
        "mmol/(8.h.kg)",
        "mmol/{Tot'Volume}",
        "mmol/d",
        "mmol/dL",
        "mmol/g",
        "mmol/g{creat}",
        "mmol/g{hemoglobin}",
        "mmol/h",
        "mmol/h/mg{Hb}",
        "mmol/h/mg{protein}",
        "mmol/kg",
        "mmol/kg/d",
        "mmol/kg/h",
        "mmol/kg/min",
        "mmol/kg{H2O}",
        "mmol/L",
        "mmol/L/s",
        "mmol/m",
        "mmol/m2",
        "mmol/min",
        "mmol/mmol",
        "mmol/mol",
        "mmol/mol{creat}",
        "mmol/s/L",
        "mo",
        "mol",
        "mol/d",
        "mol/kg",
        "mol/kg/s",
        "mol/L",
        "mol/m3",
        "mol/mL",
        "mol/mol",
        "mol/mol{creat}",
        "mol/s",
        "mosm",
        "mosm/kg",
        "mosm/L",
        "mPa",
        "ms",
        "mU",
        "mU/g",
        "mU/g{Hgb}",
        "mU/L",
        "mU/mg",
        "mU/mg{Cre}",
        "mU/min",
        "mU/mL",
        "mU/mL/min",
        "mU/mmol{creatinine}",
        "mU/mmol{RBCs}",
        "mV",
        "N",
        "N.cm",
        "N.s",
        "nCi",
        "ng",
        "ng/(24.h)",
        "ng/(8.h)",
        "ng/(8.h.kg)",
        "ng/(kg.d)",
        "ng/(kg.h)",
        "ng/(kg.min)",
        "ng/10*6",
        "ng/d",
        "ng/dL",
        "ng/dL/h",
        "ng/g",
        "ng/g{Cre}",
        "ng/g{creat}",
        "ng/h",
        "ng/kg",
        "ng/kg/(8.h)",
        "ng/kg/h",
        "ng/kg/min",
        "ng/L",
        "ng/m2",
        "ng/mg",
        "ng/mg/h",
        "ng/mg{Protein}",
        "ng/min",
        "ng/mL",
        "ng/mL/h",
        "ng/mL{rbc}",
        "ng/s",
        "nkat",
        "nL",
        "nm",
        "nm/s/L",
        "nmol",
        "nmol/(24.h)",
        "nmol/d",
        "nmol/dL",
        "nmol/g",
        "nmol/g{Cre}",
        "nmol/g{creat}",
        "nmol/g{dry_wt}",
        "nmol/h/L",
        "nmol/h/mg{protein}",
        "nmol/h/mL",
        "nmol/L",
        "nmol/L/mmol{creat}",
        "nmol/L/s",
        "nmol/L{RBCs}",
        "nmol/m/mg{protein}",
        "nmol/mg",
        "nmol/mg/h",
        "nmol/min/mg{hemoglobin}",
        "nmol/min/mg{protein}",
        "nmol/min/mL",
        "nmol/mL",
        "nmol/mL/h",
        "nmol/mL/min",
        "nmol/mmol",
        "nmol/mmol{Cre}",
        "nmol/mmol{creat}",
        "nmol/mol",
        "nmol/nmol",
        "nmol/s",
        "nmol/s/L",
        "nmol/umol{creat}",
        "ns",
        "Ohm",
        "osm/kg",
        "osm/L",
        "Pa",
        "pg",
        "pg/dL",
        "pg/L",
        "pg/mg",
        "pg/mL",
        "pg/mm",
        "pkat",
        "pL",
        "pm",
        "pmol",
        "pmol/d",
        "pmol/dL",
        "pmol/g",
        "pmol/h/mg{protein}",
        "pmol/h/mL",
        "pmol/L",
        "pmol/mg{protein}",
        "pmol/min",
        "pmol/min/mg{protein}",
        "pmol/mL",
        "pmol/mmol",
        "pmol/mmol{creat}",
        "pmol/mol",
        "pmol/umol",
        "pmol/umol{creat}",
        "ps",
        "pT",
        "s",
        "St",
        "t",
        "U",
        "U/(1.h)",
        "U/(12.h)",
        "U/(18.h)",
        "U/(2.h)",
        "U/(24.h)",
        "U/10*10{cells}",
        "U/10*12",
        "U/10*6",
        "U/10*9",
        "U/d",
        "U/dL",
        "U/g",
        "U/g{Cre}",
        "U/g{Hb}",
        "U/g{hemoglobin}",
        "U/g{Hgb}",
        "U/h",
        "U/kg/h",
        "U/kg{Hb}",
        "U/kg{hemoglobin}",
        "U/L",
        "U/min",
        "U/mL",
        "U/mL{RBC}",
        "U/mL{RBCs}",
        "U/mmol{creat}",
        "U/mol",
        "U/s",
        "U/umol",
        "u[IU]",
        "u[IU]/L",
        "u[IU]/mL",
        "ueq",
        "ueq/L",
        "ueq/mL",
        "ug",
        "ug/(24.h)",
        "ug/(8.h)",
        "ug/(kg.d)",
        "ug/(kg.h)",
        "ug/{Specimen}",
        "ug/{TotalVolume}",
        "ug/d",
        "ug/dL",
        "ug/dL{rbc}",
        "ug/g",
        "ug/g{Cre}",
        "ug/g{creat}",
        "ug/g{DryWeight}",
        "ug/g{Hgb}",
        "ug/g{Tissue}",
        "ug/h",
        "ug/kg",
        "ug/kg/(8.h)",
        "ug/kg/d",
        "ug/kg/h",
        "ug/kg/min",
        "ug/L",
        "ug/L/(24.h)",
        "ug/L{DDU}",
        "ug/m2",
        "ug/mg",
        "ug/mg{Cre}",
        "ug/mg{creat}",
        "ug/min",
        "ug/mL",
        "ug/mL{FEU}",
        "ug/mmol",
        "ug/ng",
        "ug{T4}/dL",
        "ukat",
        "uL",
        "uL/(2.h)",
        "uL/h",
        "um",
        "um/s",
        "umol",
        "umol/(24.h)",
        "umol/d",
        "umol/dL",
        "umol/g",
        "umol/g{Cre}",
        "umol/g{creat}",
        "umol/g{Hb}",
        "umol/g{hemoglobin}",
        "umol/g{Hgb}",
        "umol/h",
        "umol/h/g",
        "umol/h/L",
        "umol/h/mg{protein}",
        "umol/kg",
        "umol/L",
        "umol/L/h",
        "umol/L{rbc}",
        "umol/m",
        "umol/mg",
        "umol/mg{Cre}",
        "umol/min",
        "umol/min/g",
        "umol/min/g{prot}",
        "umol/min/g{protein}",
        "umol/min/L",
        "umol/mL",
        "umol/mL/min",
        "umol/mmol",
        "umol/mol",
        "umol/mol{Cre}",
        "umol/mol{creat}",
        "umol/mol{Hb}",
        "umol/umol",
        "uOhm",
        "us",
        "uU",
        "uU/g",
        "uU/L",
        "uU/mL",
        "uV",
        "V",
        "wk",
        "10.uN.s/(cm5.m2)",
        "10*4/uL",
        "24.h",
        "A",
        "{ARU}",
        "atm",
        "ag/{cell}",
        "Bq",
        "{binding_index}",
        "[bdsk'U]",
        "{CAG_repeats}",
        "cal",
        "cm[H2O]/s/m",
        "{delta_OD}",
        "{copies}",
        "{count}",
        "{CPM}",
        "{CPM}/10*3{cell}",
        "daL/min",
        "daL/min/m2",
        "{dilution}",
        "dyn.s/cm",
        "dyn.s/(cm.m2)",
        "{Ehrlich'U}/100.g",
        "{EIA_index}",
        "{EIA_titer}",
        "{EV}",
        "U/10",
        "U/10*10",
        "U/(10.g){feces}",
        "U/g{creat}",
        "U/g{protein}",
        "U{25Cel}/L",
        "U{37Cel}/L",
        "U/10*12{RBCs}",
        "F",
        "fmol/mg{cytosol_protein}",
        "fmol/mg{protein}",
        "{FIU}",
        "{fraction}",
        "{GAA_repeats}",
        "{genomes}/mL",
        "{Globules}/[HPF]",
        "g.m/{beat}",
        "g{creat}",
        "g{Hb}",
        "g{total_nit}",
        "g{total_prot}",
        "g{wet_tissue}",
        "g/kg/(8.h)",
        "g/(8.h){shift}",
        "g/cm3",
        "g/g{globulin}",
        "g/kg/(8.h){shift}",
        "g/kg/h",
        "g/kg/min",
        "g/mol{creat}",
        "g/{specimen}",
        "g/{total_output}",
        "g/{total_weight}",
        "Gy",
        "{beats}/min",
        "H",
        "[HPF]",
        "[GPL'U]/mL",
        "{GPS'U}",
        "[MPL'U]/mL",
        "{ISR}",
        "{IFA_index}",
        "{IFA_titer}",
        "[in_i'H2O]",
        "{index_val}",
        "{HA_titer}",
        "[IU]",
        "[IU]/L{37Cel}",
        "[IU]/mg{creat}",
        "kat",
        "kU",
        "kU/L{class}",
        "kcal/d",
        "kcal/kg/(24.h)",
        "kcal/[oz_av]",
        "[ka'U]",
        "L/(24.h)",
        "L/s/s2",
        "{Log_copies}/mL",
        "{Log_IU}",
        "{Log_IU}/mL",
        "{Log}",
        "[LPF]",
        "lm",
        "lm.m2",
        "{Lyme_index_value}",
        "[mclg'U]",
        "Ms",
        "ug/g{feces}",
        "ug{FEU}/mL",
        "ug/(100.g)",
        "ug/m3",
        "ug/dL{RBCs}",
        "ug/g{dry_tissue}",
        "ug/g{dry_wt}",
        "ug/g{hair}",
        "ug/g{Hb}",
        "ug/g{tissue}",
        "ug/L{RBCs}",
        "ug/mL{class}",
        "ug/mL{eqv}",
        "ug/mmol{creat}",
        "ug/{specimen}",
        "ug/[sft_i]",
        "umol{BCE}/mol",
        "umol/(2.h)",
        "umol/(8.h)",
        "umol/dL{GF}",
        "umol/kg{feces}",
        "umol/L{RBCs}",
        "umol/umol{creat}",
        "umol/mg{creat}",
        "umol/mmol{creat}",
        "umol/min/g{mucosa}",
        "mU/mmol{creat}",
        "mU/g{Hb}",
        "mU/g{protein}",
        "mU/mg{creat}",
        "mbar/L/s",
        "meq/g{creat}",
        "meq/{specimen}",
        "meq/{total_volume}",
        "mg{FEU}/L",
        "mg/(6.h)",
        "mg/{collection}",
        "mg/d/{1.73_m2}",
        "mg/dL{RBCs}",
        "mg/g{dry_tissue}",
        "mg/g{feces}",
        "mg/g{tissue}",
        "mg/g{wet_tissue}",
        "mg/kg/(8.h)",
        "mg/kg/h",
        "mg/L{RBCs}",
        "mg/mg{creat}",
        "mg/{specimen}",
        "mg/{total_output}",
        "mg/{total_volume}",
        "mL{fetal_RBCs}",
        "mL/(5.h)",
        "mL/(6.h)",
        "mL/{beat}",
        "mL/{beat}/m2",
        "mmol/(5.h)",
        "mmol/{ejaculate}",
        "mmol/kg/(8.h)",
        "mmol/L{RBCs}",
        "mmol/mmol{urea}",
        "mmol/mmol{creat}",
        "mmol/{specimen}",
        "mmol/{total_vol}",
        "10*6.[CFU]/L",
        "10*6.[IU]",
        "10*6/(24.h)",
        "mPa.s",
        "{minidrop}/min",
        "{minidrop}/s",
        "{molecule}/{platelet}",
        "{mm/dd/yyyy}",
        "{mutation}",
        "nU/mL",
        "nU/{RBC}",
        "ng{FEU}/mL",
        "ng/U",
        "ng/mg{creat}",
        "ng/mg{protein}",
        "ng/mL{RBCs}",
        "ng/10*6{RBCs}",
        "nmol{BCE}",
        "nmol{BCE}/L",
        "nmol{BCE}/mmol{creat}",
        "nmol{1/2cys}/mg{protein}",
        "nmol{ATP}",
        "nmol/dL{GF}",
        "nmol/mg{creat}",
        "nmol/mg{protein}",
        "nmol/mg{protein}/h",
        "nmol/min",
        "nmol/min/mg{Hb}",
        "nmol/min/10*6{cells}",
        "{#}/[HPF]",
        "{#}/L",
        "{#}/[LPF]",
        "{#}/uL",
        "{#}/mL",
        "{#}/min",
        "Ohm.m",
        "osm",
        "{Pan_Bio'U}",
        "/10*4{RBCs}",
        "/m3",
        "/{entity}",
        "/g{Hb}",
        "/g{tot_nit}",
        "/g{tot_prot}",
        "/g{wet_tis}",
        "/[IU]",
        "/kg{body_wt}",
        "/mm",
        "/mmol{creat}",
        "/{OIF}",
        "/10*3",
        "/10*3.{RBCs}",
        "/10*12{RBCs}",
        "%{loss_AChR}",
        "%{penetration}",
        "%{abnormal}",
        "%{activity}",
        "%{aggregation}",
        "%{at_60_min}",
        "%{basal_activity}",
        "%{binding}",
        "%{blockade}",
        "%{blocked}",
        "%{bound}",
        "%{breakdown}",
        "%{deficient}",
        "%{dose}",
        "%{excretion}",
        "%{Hb}",
        "%{hemolysis}",
        "%{index}",
        "%{inhibition}",
        "%{loss}",
        "%{lysis}",
        "%{normal}",
        "%{normal_pooled_plasma}",
        "%{bacteria}",
        "%{baseline}",
        "%{cells}",
        "%{RBCs}",
        "%{WBCs}",
        "%{positive}",
        "%{reactive}",
        "%{recovery}",
        "%{reference}",
        "%{residual}",
        "%{saturation}",
        "%{total}",
        "%{uptake}",
        "%{viable}",
        "{percentile}",
        "{phenotype}",
        "pA",
        "pg/{cell}",
        "pg/mg{creat}",
        "pg/{RBC}",
        "pmol/(24.h)",
        "pmol/{RBC}",
        "[pt_us]",
        "%{relative}",
        "{relative_saturation}",
        "{Rubella_virus}",
        "{saturation}",
        "s/{control}",
        "S",
        "Sv",
        "{s_co_ratio}",
        "{STDV}",
        "T",
        "10*3{copies}/mL",
        "10*3{RBCs}",
        "{TSI_index}",
        "Wb",
        "{WBCs}",
        "1",
        "'",
        "''",
        "%[slope]",
        "%{Bound}",
        "/100{Spermatozoa}",
        "/g{HGB}",
        "[acr_br]",
        "[acr_us]",
        "[Amb'a'1'U]",
        "[bbl_us]",
        "[bf_i]",
        "[Btu]",
        "[Btu_39]",
        "[Btu_59]",
        "[Btu_60]",
        "[Btu_IT]",
        "[Btu_m]",
        "[Btu_th]",
        "[bu_br]",
        "[bu_us]",
        "[c]",
        "[Cal]",
        "[car_Au]",
        "[car_m]",
        "[CCID_50]",
        "[cft_i]",
        "[ch_br]",
        "[ch_us]",
        "[cicero]",
        "[cml_i]",
        "[cr_i]",
        "[crd_us]",
        "[cyd_i]",
        "[D'ag'U]",
        "[didot]",
        "[diop]",
        "[dpt_us]",
        "[dqt_us]",
        "[dr_ap]",
        "[dye'U]",
        "[e]",
        "[eps_0]",
        "[fdr_br]",
        "[FFU]",
        "[ft_br]",
        "[ft_us]",
        "[fth_br]",
        "[fth_us]",
        "[fur_us]",
        "[G]",
        "[gal_wi]",
        "[gil_br]",
        "[gil_us]",
        "[h]",
        "[hd_i]",
        "[hnsf'U]",
        "[HP]",
        "[hp_C]",
        "[hp_M]",
        "[hp_Q]",
        "[hp_X]",
        "[in_br]",
        "[in_i'Hg]",
        "[in_us]",
        "[iU]/dL",
        "[iU]/g",
        "[iU]/kg",
        "[iU]/L",
        "[iU]/mL",
        "[k]",
        "[kn_br]",
        "[kn_i]",
        "[knk'U]",
        "[lb_ap]",
        "[lb_tr]",
        "[lbf_av]",
        "[lcwt_av]",
        "[Lf]",
        "[ligne]",
        "[lk_br]",
        "[lk_us]",
        "[lne]",
        "[lton_av]",
        "[ly]",
        "[m_e]",
        "[m_p]",
        "[mesh_i]",
        "[MET]",
        "[mi_br]",
        "[mil_i]",
        "[mil_us]",
        "[min_br]",
        "[mu_0]",
        "[nmi_br]",
        "[oz_ap]",
        "[pc_br]",
        "[pca]",
        "[pca_pr]",
        "[p'diop]",
        "[PFU]",
        "[pi]",
        "[pied]",
        "[pk_br]",
        "[pk_us]",
        "[pnt]",
        "[pnt_pr]",
        "[PNU]",
        "[pouce]",
        "[PRU]",
        "[pwt_tr]",
        "[rch_us]",
        "[rd_br]",
        "[rd_us]",
        "[rlk_us]",
        "[S]",
        "[sc_ap]",
        "[sct]",
        "[scwt_av]",
        "[smgy'U]",
        "[smi_us]",
        "[smoot]",
        "[srd_us]",
        "[stone_av]",
        "[TCID_50]",
        "[twp]",
        "[USP'U]",
        "[yd_br]",
        "[yd_us]",
        "{Cells}/uL",
        "{Copies}/mL",
        "{Ct}",
        "{Ehrlich_U}/dL",
        "{EhrlichU}/dL",
        "{Elisa_U}/mL",
        "{ElisaU}/mL",
        "{kp_C}",
        "{rbc}",
        "{Spermatozoa}/mL",
        "{tbl}",
        "{tot}",
        "10*",
        "10^",
        "a_g",
        "a_j",
        "a_t",
        "Ao",
        "ar",
        "AU",
        "b",
        "B",
        "B[kW]",
        "B[mV]",
        "B[SPL]",
        "B[uV]",
        "B[V]",
        "B[W]",
        "Bd",
        "Bi",
        "bit",
        "bit_s",
        "By",
        "C",
        "cal_[15]",
        "cal_[20]",
        "cal_IT",
        "cal_m",
        "cal_th",
        "cd",
        "Ci",
        "circ",
        "dyn",
        "G",
        "g%",
        "g.m/{H.B.}",
        "Gal",
        "Gb",
        "gf",
        "gon",
        "k[iU]/mL",
        "kg{wet'tis}",
        "Ky",
        "Lmb",
        "lx",
        "m[H2O]",
        "m[Hg]",
        "mg/{TotalVolume}",
        "mg/mg{Cre}",
        "mg{creat}",
        "mho",
        "mmol/{TotalVolume}",
        "mmol/mol{Cre}",
        "mo_g",
        "mo_j",
        "mo_s",
        "Mx",
        "Np",
        "Oe",
        "P",
        "pc",
        "ph",
        "R",
        "rad",
        "RAD",
        "REM",
        "sb",
        "sph",
        "sr",
        "st",
        "u",
        "uCi",
        "W",
    ]
    VALID_UNIT_DESCRIPTIONS = [
        "percent",
        "percent / 100 WBC",
        "percent 0to3Hours",
        "percent Abnormal",
        "percent Activity",
        "percent BasalActivity",
        "percent Binding",
        "percent Blockade",
        "percent Carboxyhemoglobin",
        "percent Conversion",
        "percent Cound",
        "percent EosSeen",
        "percent Excretion",
        "percent Fat",
        "percent FetalErythrocytes",
        "percent Hemoglobin",
        "percent HemoglobinA1C",
        "percent HemoglobinSaturation",
        "percent Hemolysis",
        "percent HumanResponse",
        "percent Index",
        "percent Inhibition",
        "percent Live",
        "percent Negative Control",
        "percent Normal",
        "percent NormalControl",
        "percent NormalPooledPlasma",
        "percent ofAvailable",
        "percent ofBacteria",
        "percent OfLymphocytes",
        "percent OfWBCs",
        "percent Oxygen",
        "percent Positive",
        "percent Precipitate",
        "percent Reactivity",
        "percent response",
        "percent risk",
        "percent SpermMotility",
        "percent Total",
        "percent TotalProtein",
        "percent Tot'Cholesterol",
        "percent Tot'Hgb",
        "percent Uptake",
        "VolumePercent",
        "percent WeightToWeight",
        "per 12 * hour",
        "per arbitrary unit",
        "per high power field",
        "per international unit",
        "per low power field",
        "per Entity",
        "per hpf",
        "per LPF",
        "per oif",
        "per Specimen",
        "per tot",
        "PerTenGiga",
        "PerTrillion",
        "PerTrillionRedBloodCells",
        "PerMillion",
        "PerBillion",
        "per 100",
        "per 100 cells",
        "per 100 neutrophils",
        "per 100 spermatozoa",
        "Per100WBC",
        "Per100WBC",
        "/ year",
        "per centimeter of water",
        "per day",
        "per deciliter",
        "per gram",
        "per gram creat",
        "per gram hgb",
        "per gram tot'nit",
        "per gram tot'prot",
        "per gram wet'tis",
        "per hour",
        "per kilogram",
        "per kilogram body wt",
        "per liter",
        "per square meter",
        "per milligram",
        "per minute",
        "per milliliter",
        "per cubic millimeter",
        "per millimole",
        "per month",
        "per second",
        "per enzyme unit",
        "per microgram",
        "per microliter",
        "per week",
        "IgA anticardiolipin unit",
        "IgA anticardiolipin unit per milliliter",
        "arbitrary unit",
        "arbitary unit / liter",
        "arbitrary unit per milliliter",
        "allergy unit",
        "bioequivalent allergen unit",
        "Bethesda unit",
        "Bethesda unit",
        "colony forming unit",
        "colony forming unit per liter",
        "colony forming unit per milliliter",
        "French (catheter gauge)",
        "cubic inch",
        "cup",
        "degree Fahrenheit",
        "Dram (US and British)",
        "drop",
        "drop / HPF",
        "drop / hour",
        "drop / minute",
        "drop / milliliter",
        "drop / second",
        "fluid dram",
        "fluid ounce",
        "fluid ounce",
        "Feet",
        "fathom",
        "gallon",
        "Queen Anne's wine gallon",
        "IgG anticardiolipin unit",
        "grain",
        "inch (international)",
        "international unit",
        "international unit per 2 hour",
        "international unit per 24 hour",
        "international unit per billion red blood cells",
        "international unit per day",
        "international unit per deciliter",
        "international unit per gram",
        "international unit per gram of hemoglobin",
        "international unit / gram Hgb",
        "international unit per hour",
        "international unit per kilogram",
        "international unit per kilogram per day",
        "international unit per liter",
        "international unit per minute",
        "international unit per milliliter",
        "pound (US and British)",
        "statute mile",
        "mile",
        "minim",
        "IgM anticardiolipin unit",
        "nautical mile",
        "ounce (US and British)",
        "ounce",
        "pH",
        "the number pi * radian / minute",
        "part per billion",
        "part per million",
        "part per million in volume per volume",
        "part per trillion",
        "parts per thousand",
        "parts per trillion",
        "pound per square inch",
        "pint",
        "quart",
        "quart",
        "square foot (international)",
        "square inch (international)",
        "short ton U.S. ton",
        "square yard",
        "tablespoon (US)",
        "tuberculin unit",
        "Todd unit",
        "Todd unit",
        "teaspoon",
        "yard",
        "# of calculi",
        "# of donor informative markers",
        "# of fetuses",
        "# of informative markers",
        "#",
        "2 or 3 times / day",
        "3 times / day",
        "4 times / day",
        "5 times / day",
        "absorbance",
        "Absorbance'U",
        "Absorbance'U / milliliter",
        "activity",
        "ActivityCoefficient",
        "AHF'U",
        "AntibodyResponse'U",
        "Applicator",
        "IgA antiphosphatidylserine unit",
        "AspirinReaction'U",
        "Bead",
        "Beats / minute",
        "Bottle",
        "Bowls / day",
        "Breaths / minute",
        "complement activity enzyme unit",
        "CagRepeat",
        "Can",
        "Cans / week",
        "Capsule",
        "Cell",
        "cells",
        "cells per high power field",
        "Cells / milliliter",
        "cells per microliter",
        "CfTiter",
        "cfu",
        "cfu / milliliter",
        "CGG_repeats",
        "CGG",
        "complement CH100 unit",
        "clock time",
        "clock_time",
        "ComplementActivityEnzyme'U",
        "ComplementCH100'U",
        "ComplementCH50'U",
        "copies per milliliter",
        "copies per microgram",
        "Copies / microliter",
        "Count",
        "Counts / minute",
        "Dalton",
        "DdTiter",
        "DeltaOpticalDensity",
        "dilution",
        "Disintegrations / minute",
        "Dose",
        "Drinks / day",
        "Each",
        "Ehrlich unit",
        "Ehrlich unit per 2 hour",
        "Ehrlich unit per 100 gram",
        "Ehrlich unit per day",
        "Ehrilich unit per deciliter",
        "Ehrlich'U / milliliter",
        "EIA index",
        "EIA titer",
        "EIA unit",
        "EIA unit per enzyme Unit",
        "ElisaIndex",
        "ELISA unit",
        "Elisa'U / milliliter",
        "ElisaValue",
        "erythrocyte per microliter",
        "Events",
        "FluorescenceIntensity'U",
        "G unit",
        "GliadinIndexValue",
        "G-PortionPhospholipids",
        "HaTiter",
        "IfaIndex",
        "IfaTiter",
        "IgAAntiphosphatidyleserine'U",
        "IgAPhospholipid'U",
        "IgGAntiphosphatidyleserine'U",
        "IgGIndex",
        "IgMAntiphosphatidyleserine'U",
        "IgMIndex",
        "immune complex unit",
        "ImmuneStatusRatio",
        "Immunity",
        "Index_val",
        "index",
        "IndexValue",
        "InhaledTobaccoUseAmountYears",
        "InhaledTobaccoUsePacks / day",
        "international normalized ratio",
        "INR'unit",
        "Juvenile Diabetes Foundation unit",
        "Juvenile Diabetes Foundation unit per liter",
        "JuvenileDiabetesFound'U",
        "kaolin clotting time",
        "Kronus unit per liter",
        "Kronus unit per milliliter",
        "lgCopies / milliliter",
        "log (base 10) copies per milliliter",
        "log (base 10) international unit per milliliter",
        "LymeIndexValue",
        "M.o.M.",
        "multiple of the median",
        "Markers",
        "minidrp",
        "Molecule / Platelet",
        "M-PortionPhospholipids",
        "IgM antiphosphatidylserine unit",
        "IgM antiphosphatidylserine unit per milliliter",
        "MultOfMean",
        "NonspecificOunce",
        "Number",
        "optical density unit",
        "Once / day",
        "OpticalDensity",
        "OpticalDensityIndex",
        "OpticalDensityRatio",
        "P2Y12 Reaction Units",
        "Package",
        "Packs / day",
        "PackYears",
        "Patch",
        "Percentile",
        "Pill",
        "Pouches / week",
        "RadioactiveT3UptakeRatio",
        "ratio",
        "red blood cell per microliter",
        "RecTiter",
        "Relative'U",
        "RelativeViscosity",
        "RPI'U",
        "RubellaVirus",
        "SatIndex",
        "Scoop",
        "ScoreOf",
        "shift",
        "spermatozoa per milliliter",
        "spray",
        "StandardDeviation",
        "StandardIgA'U",
        "StandardIgG'U",
        "StandardIgM'U",
        "StdDeviation'U",
        "StimulatingIndex",
        "Streptozyme'U",
        "ThyroxinUptake'U",
        "TIBC'U",
        "Times / week",
        "Tine'U",
        "titer",
        "ToxoplasmaIndexValue",
        "Vial",
        "Volume / Vvolume",
        "WeeksDays",
        "WhiteBloodCell",
        "one per day",
        "one per minute",
        "trillion per liter",
        "Thousand",
        "Thousand Red Blood Cells",
        "Thousand Per * Unit",
        "Thousand Per Liter",
        "Thousand Per MilliLiter",
        "Thousands Per MicroLiter",
        "Thousand Copies Per MilliLiter",
        "(the number ten for arbitrary powers ^ -3) Polarization'U",
        "OneHundredThousand",
        "Million",
        "MillionInternationalUnit",
        "MillionEquivalentsPerMilliLiter",
        "(the number ten for arbitrary powers ^ 6) * Unit",
        "MillionPerSpecimen",
        "million per kilogram",
        "million per liter",
        "million per milliliter",
        "(the number ten for arbitrary powers ^ 6) / (millimeter ^ 3)",
        "million per microliter",
        "(the number ten for arbitrary powers ^ -6) Immunofluorescence'U",
        "TenToEighth",
        "billion per liter",
        "billion per milliliter",
        "billion per microliter",
        "10 liter per minute per square meter",
        "10 liter per minute",
        "10 * microNewton * second / centimeter * (meter ^ 2)",
        "10 * microNewton * second / centimeter",
        "10 * microNewton * second / (centimeter ^ 2)",
        "year",
        "Ampère / meter",
        "technical atmosphere",
        "bar",
        "degree Celsius",
        "centigram",
        "centiliter",
        "centimeter",
        "centimeter of water",
        "centimeter of water column / second * meter",
        "centimeter of water per liter per second",
        "centimeter of mercury",
        "square centimeter",
        "square centimeter per second",
        "cubic centimeter",
        "centiPoise",
        "centiStokes",
        "day",
        "decibel",
        "degree",
        "degree per second",
        "decigram",
        "deciliter",
        "decimeter",
        "square decimeter per square second",
        "equivalents",
        "equivalents / liter",
        "equivalents / milliliter",
        "equivalents / millimole",
        "equivalents / micromole",
        "erg",
        "electronvolt",
        "femtogram",
        "femtoliter",
        "femtoliter / nanoliter",
        "femtometer",
        "femtomole",
        "femtomole per gram",
        "femtomole per liter",
        "femtomole / milligram",
        "femtomole / milliliter",
        "gram",
        "gram * meter",
        "gram * meter / hb * (meter ^ 2)",
        "gram * meter / hb",
        "gram per 100 gram",
        "gram per 12 hour",
        "gram per 24 hour",
        "gram per 3 days",
        "gram per 4 hour",
        "gram per 48 hour",
        "gram per 5 hour",
        "gram per 6 hour",
        "gram per 72 hour",
        "gram / 8 * hour",
        "gram / 8 * kilogram * hour",
        "gram / kilogram * hour",
        "gram / kilogram * minute",
        "gram / TotalWeight",
        "gram per day",
        "gram per deciliter",
        "gram per gram",
        "gram / gram Cre",
        "gram / gram creat",
        "gram per gram of tissue",
        "gram per hour",
        "gram per hour per square meter",
        "gram per kilogram",
        "gram per kilogram per day",
        "gram per liter",
        "grams Per Square Meter",
        "gram per milligram",
        "gram per minute",
        "gram per milliliter",
        "gram per millimole",
        "gram / millimole creat",
        "gram per mole",
        "gigaBecquerel",
        "hour",
        "hectoliter",
        "Hertz",
        "international unit",
        "joule",
        "joule per liter",
        "Kelvin",
        "Kelvin / Watt",
        "kilo international unit per liter",
        "kilo international unit per milliliter",
        "katal / kilogram",
        "katal / liter",
        "kiloBecquerel",
        "kilocalorie",
        "kilocalorie / 8 * hour",
        "kilocalorie per hour",
        "kilogram",
        "kilogram meter per second",
        "kilogram per second per square meter",
        "kilogram per hour",
        "kilogram per liter",
        "kilogram / (meter ^ 2)",
        "kilogram / (meter ^ 3)",
        "kilogram / minute",
        "kilogram per mole",
        "kilogram / second",
        "kiloliter",
        "kilometer",
        "kiloPascal",
        "kilosecond",
        "kiloenzyme Unit per gram",
        "kiloUnit / hour",
        "kiloenzyme Unit per liter",
        "kilo enzyme unit per milliliter",
        "liter",
        "liter * (second ^ 2) / second",
        "liter per 8 hour",
        "liter per minute per square meter",
        "liter per day",
        "liter per hour",
        "liter per kilogram",
        "liter per liter",
        "liter per minute",
        "liter / second",
        "lumen / (meter ^ 2)",
        "meter",
        "meter per second",
        "meter per square second",
        "milliinternational unit",
        "milli international unit per liter",
        "milli international unit per milliliter",
        "square meter",
        "square meter per second",
        "cubic meter per second",
        "milliAmpère",
        "millibar",
        "millibar second per liter",
        "megaBecquerel",
        "milliCurie",
        "milliequivalent",
        "milliequivalent per 12 hour",
        "milliequivalent per 2 hour",
        "milliequivalent per 24 hour",
        "milliequivalent per 8 hour",
        "milliequivalents / 8 * hour * kilogram",
        "milliequivalents / kilogram * day",
        "milliequivalents / Specimen",
        "milliequivalent per day",
        "milliequivalent per deciliter",
        "milliequivalent per gram",
        "milliequivalents / gram Cre",
        "milliequivalent per hour",
        "milliequivalent per kilogram",
        "milliequivalent per kilogram per hour",
        "milliequivalents / kilogram / minute",
        "milliequivalent per liter",
        "milliequivalent per square meter",
        "milliequivalent per minute",
        "milliequivalent per milliliter",
        "milligram",
        "milligram per 10 hour",
        "milligram per 12 hour",
        "milligram per 18 hour",
        "milligram per 2 hour",
        "milligram per 24 hour",
        "milligram per 72 hour",
        "milligram per 8 hour",
        "milligram / 8 * hour * kilogram",
        "milligram / kilogram * hour",
        "milligram / Hgb / gram",
        "milligram / Specimen",
        "milligram / Tot'Volume",
        "milligram / Volume",
        "milligram per day",
        "milligram / day / 173 * (the number ten for arbitrary powers ^ -2) * (meter ^ 2)",
        "milligram per deciliter",
        "milligram per gram",
        "milligram / gram Cre",
        "milligram per gram of creatinine",
        "milligram per hour",
        "milligram per kilogram",
        "milligram / kilogram / 24 * hour",
        "milligram per kilogram per day",
        "milligram per kilogram per minute",
        "milligram per liter",
        "milligram per square meter",
        "milligram per cubic meter",
        "milligram per milligram",
        "milligram / milligram cre",
        "milligram per minute",
        "milligram per milliliter",
        "milligram per millimole",
        "milligram / millimole Cre",
        "milligram per millimole of creatinine",
        "milligram per week",
        "milligram Phenylketones / deciliter",
        "minute",
        "milliliter",
        "milliliter / h'b * (meter ^ 2)",
        "milliliter per 10 hour",
        "milliliter per 12 hour",
        "milliliter per 2 hour",
        "milliliter per 24 hour",
        "milliliter per 4 hour",
        "milliliter per 72 hour",
        "milliliter per 8 hour",
        "milliliter / kilogram * minute",
        "milliliter per square inch (international)",
        "MilliLitersPerHeartbeat [SI Volume Units]",
        "milliliter / centimeter of water column",
        "milliliter per day",
        "milliliter per deciliter",
        "milliliter per hour",
        "milliliter per kilogram",
        "milliliter per kilogram per 8 hour",
        "milliliter per kilogram per day",
        "milliliter per kilogram per hour",
        "milliliter per kilogram per minute",
        "milliliter per liter",
        "milliliter per square meter",
        "milliliter per millibar",
        "milliliter per minute",
        "milliliter / minute / 173 * (the number ten for arbitrary powers ^ -2) * (meter ^ 2)",
        "milliliter per minute per 1.73 square meter",
        "milliliter per minute per square meter",
        "milliliter per millimeter",
        "milliliter per second",
        "millimeter",
        "millimeter per hour",
        "millimeter per minute",
        "millimeter of water",
        "millimeter of mercury",
        "square millimeter",
        "cubic millimeter",
        "millimole",
        "millimole per 12 hour",
        "millimole per 18 hour",
        "millimole per 2 hour",
        "millimole per 24 hour",
        "millimole per 6 hour",
        "millimole per 8 hour",
        "millimole / 8 * hour * kilogram",
        "millimole / Tot'Volume",
        "millimole per day",
        "millimole per deciliter",
        "millimole per gram",
        "millimole per gram of creatinine",
        "millimole per gram of hemoglobin",
        "millimole per hour",
        "millimole per hour per milligram of hemoglobin",
        "millimole per hour per milligram of protein",
        "millimole per kilogram",
        "millimole per kilogram per day",
        "millimole per kilogram per hour",
        "millimole per kilogram per minute",
        "millimole per kilogram of water",
        "millimole per liter",
        "millimole per liter per second",
        "millimole / meter",
        "millimole per square meter",
        "millimole per minute",
        "millimole per millimole",
        "millimole per mole",
        "millimole per mole of creatinine",
        "millimole per second per liter",
        "month",
        "mole",
        "mole per day",
        "mole per kilogram",
        "mole per kilogram per second",
        "mole per liter",
        "mole per cubic meter",
        "mole per milliliter",
        "mole per mole",
        "mole / mole creat",
        "mole per second",
        "milliosmole",
        "milliosmole per kilogram",
        "milliosmole per liter",
        "millipascal",
        "millisecond",
        "millienzyme Unit",
        "millienzyme Unit per gram",
        "milliUnit / gram Hgb",
        "millienzyme Unit per liter",
        "milliUnit / milligram",
        "milliUnit / milligram Cre",
        "milliUnit / minute",
        "millienzyme Unit per milliliter",
        "millienzyme Unit per milliliter per minute",
        "millienzyme Unit per millimole of creatinine",
        "millienzyme Unit per millimole of red blood cells",
        "milliVolt",
        "Newton",
        "Newton centimeter",
        "Newton second",
        "nanoCurie",
        "nanogram",
        "nanogram per 24 hour",
        "nanogram per 8 hour",
        "nanogram / 8 * hour * kilogram",
        "nanogram / kilogram * day",
        "nanogram / kilogram * hour",
        "nanogram / kilogram * minute",
        "nanogram per million",
        "nanogram per day",
        "nanogram per deciliter",
        "nanogram / deciliter / hour",
        "nanogram per gram",
        "nanogram / gram Cre",
        "nanogram per gram of creatinine",
        "nanogram per hour",
        "nanogram per kilogram",
        "nanogram per kilogram per 8 hour",
        "nanogram per kilogram per hour",
        "nanogram per kilogram per minute",
        "nanogram per liter",
        "nanogram per square meter",
        "nanogram per milligram",
        "nanogram per milligram per hour",
        "nanogram / milligram Protein",
        "nanogram per minute",
        "nanogram per millliiter",
        "nanogram per milliliter per hour",
        "nanogram / milliliter rbc",
        "nanogram per second",
        "nanokatal",
        "nanoliter",
        "nanometer",
        "nanometer per second per liter",
        "nanomole",
        "nanomole per 24 hour",
        "nanomole per day",
        "nanomole per deciliter",
        "nanomole per gram",
        "nanomole / gram Cre",
        "nanomole per gram of creatinine",
        "nanomole per gram of dry weight",
        "nanomole per hour per liter",
        "nanomole per hour per milligram of protein",
        "nanomole per hour per milliliter",
        "nanomole per liter",
        "nanomole per liter per millimole of creatinine",
        "nanomole per liter per second",
        "nanomole per liter of red blood cells",
        "nanomole per meter per milligram of protein",
        "nanomole per milligram",
        "nanomole per milligram per hour",
        "nanomole per minute per milligram of hemoglobin",
        "nanomole per minute per milligram of protein",
        "nanomole per minute per milliliter",
        "nanomole per milliliter",
        "nanomole per milliliter per hour",
        "nanomole per milliliter per minute",
        "nanomole per millimole",
        "nanomole / millimole Cre",
        "nanomole per millimole of creatinine",
        "nanomole per mole",
        "nanomole per nanomole",
        "nanomole per second",
        "nanomole per second per liter",
        "nanomole per micromole of creatinine",
        "nanosecond",
        "Ohm",
        "osmole per kilogram",
        "osmole per liter",
        "Pascal",
        "picogram",
        "picogram per deciliter",
        "picogram per liter",
        "picogram per milligram",
        "picogram per milliliter",
        "picogram per millimeter",
        "picokatal",
        "picoliter",
        "picometer",
        "picomole",
        "picomole per day",
        "picomole per deciliter",
        "picomole per gram",
        "picomole per hour per milligram of protein",
        "picomole per hour per milliliter",
        "picomole per liter",
        "picomole per milligram of protein",
        "picomole per minute",
        "picomole per minute per milligram of protein",
        "picomole per milliliter",
        "picomole per millimole",
        "picomole per millimole of creatinine",
        "picomole per mole",
        "picomole per micromole",
        "picomole per micromole of creatinine",
        "picosecond",
        "picotesla",
        "second",
        "Stokes",
        "tonne",
        "enzyme Unit",
        "enzyme Unit per 1 hour",
        "enzyme unit per 12 hour",
        "enzyme Unit per 18 hour",
        "enzyme unit per 2 hour",
        "enzyme unit per 24 hour",
        "enzyme unit per 10 billion cells",
        "enzyme unit per trillion",
        "enzyme unit per million",
        "enzyme unit per billion",
        "enzyme unit per day",
        "enzyme unit per deciliter",
        "enzyme unit per gram",
        "Unit / gram Cre",
        "enzyme unit per gram of hemoglobin",
        "enzyme Unit per gram of hemoglobin",
        "UnitsPerGramHemoglobin",
        "enzyme unit per hour",
        "Unit / kilogram / hour",
        "enzyme unit per kilogram of hemoglobin",
        "enzyme Unit per kilogram of hemoglobin",
        "enzyme unit per liter",
        "enzyme unit per minute",
        "enzyme unit per milliliter",
        "Unit / milliliter RBC",
        "enzyme unit per milliliter of red blood cells",
        "enzyme unit per millimole of creatinine",
        "enzyme Unit per mole",
        "enzyme unit per second",
        "enzyme Unit per micromole",
        "micro international unit",
        "microinternational unit per liter",
        "micro international unit per milliliter",
        "microequivalents",
        "microequivalent per liter",
        "microequivalent per milliliter",
        "microgram",
        "microgram per 24 hour",
        "microgram per 8 hour",
        "microgram / kilogram * day",
        "microgram / kilogram * hour",
        "microgram / Specimen",
        "MicroGramsPerTotalVolume",
        "microgram per day",
        "microgram per deciliter",
        "microgram / deciliter rbc",
        "microgram per gram",
        "microgram / gram Cre",
        "microgram per gram of creatinine",
        "microgram / gram DryWeight",
        "microgram / gram Hgb",
        "microgram / gram Tissue",
        "microgram per hour",
        "microgram per kilogram",
        "microgram per kilogram per 8 hour",
        "microgram per kilogram per day",
        "microgram per kilogram per hour",
        "microgram per kilogram per minute",
        "microgram per liter",
        "microgram per liter per 24 hour",
        "microgram / liter DDU",
        "microgram per square meter",
        "microgram per milligram",
        "microgram / milligram Cre",
        "microgram per milligram of creatinine",
        "microgram per minute",
        "microgram per milliliter",
        "microgram / milliliter FEU",
        "microgram per millimole",
        "microgram per nanogram",
        "microgram T4 / deciliter",
        "microkatal",
        "microliter",
        "microliter per 2 hour",
        "microliter per hour",
        "micrometer",
        "micrometer per second",
        "micromole",
        "micromole per 24 hour",
        "micromole per day",
        "micromole per deciliter",
        "micromole per gram",
        "micromole / gram Cre",
        "micromole per gram of creatinine",
        "micromole per gram of hemoglobin",
        "micromole per gram of hemoglobin",
        "micromole / gram Hgb",
        "micromole per hour",
        "micromole / hour / gram",
        "micromole per hour per liter",
        "micromole per hour per milligram of protein",
        "micromole per kilogram",
        "micromole per liter",
        "micromole per liter per hour",
        "micromole per liter of red blood cells",
        "micromole / meter",
        "micromole per milligram",
        "micromole / milligram Cre",
        "micromole per minute",
        "micromole per minute per gram",
        "micromole / minute / gram prot",
        "micromole per minute per gram of protein",
        "micromole per minute per liter",
        "micromole per milliliter",
        "micromole per milliliter per minute",
        "micromole per millimole",
        "micromole per mole",
        "micromole / mole Cre",
        "micromole per mole of creatinine",
        "micromole per mole of hemoglobin",
        "micromole per micromole",
        "microOhm",
        "microsecond",
        "microUnit",
        "micro enzyme unit per gram",
        "micro enzyme unit per liter",
        "micro enzyme unit per milliliter",
        "microvolt",
        "volt",
        "week",
        "10 micronewton second per centimeter to the fifth power per square meter",
        "10 thousand per microliter",
        "24 hour",
        "Ampère",
        "aspirin response unit",
        "standard atmosphere",
        "attogram per cell",
        "Becquerel",
        "binding index",
        "Bodansky unit",
        "CAG trinucleotide repeats",
        "calorie",
        "centimeter of water per second per meter",
        "change in (delta) optical density",
        "copies",
        "count",
        "counts per minute",
        "counts per minute per thousand cells",
        "dekaliter per minute",
        "dekaliter per minute per square meter",
        "dilution",
        "dyne second per centimeter",
        "dyne second per centimeter per square meter",
        "Ehrlich unit per 100 gram",
        "EIA index",
        "EIA titer",
        "EIA value",
        "enzyme unit per 10",
        "enzyme unit per 10 billion",
        "enzyme unit per 10 gram of feces",
        "enzyme unit per gram of creatinine",
        "enzyme unit per gram of protein",
        "enzyme unit per liter at 25 deg Celsius",
        "enzyme unit per liter at 37 deg Celsius",
        "enzyme unit per trillion red blood cells",
        "Farad",
        "femtomole per milligram of cytosol protein",
        "femtomole per milligram of protein",
        "fluorescent intensity unit",
        "fraction",
        "GAA trinucleotide repeats",
        "genomes per milliliter",
        "globules (drops) per high power field",
        "gram meter per heart beat",
        "gram of creatinine",
        "gram of hemoglobin",
        "gram of total nitrogen",
        "gram of total protein",
        "gram of wet tissue",
        "gram per kilogram per 8 hour",
        "gram per 8 hour shift",
        "gram per cubic centimeter",
        "gram per gram of globulin",
        "gram per kilogram per 8 hour shift",
        "gram per kilogram per hour",
        "gram per kilogram per minute",
        "gram per mole of creatinine",
        "gram per specimen",
        "gram per total output",
        "gram per total weight",
        "Gray",
        "heart beats per minute",
        "Henry",
        "high power field",
        "IgG anticardiolipin unit per milliliter**",
        "IgG antiphosphatidylserine unit",
        "IgM anticardiolipin unit per milliliter**",
        "immune status ratio",
        "immunofluorescence assay index",
        "Immunofluorescence assay titer",
        "inch (international) of water",
        "index value",
        "influenza hemagglutination titer",
        "international unit",
        "international unit per liter at 37 degrees Celsius",
        "international unit per milligram of creatinine",
        "katal",
        "kilo enzyme unit",
        "kilo enzyme unit per liter class",
        "kilocalorie per day",
        "kilocalorie per kilogram per 24 hour",
        "kilocalorie per ounce (US & British)",
        "King Armstrong unit",
        "liter per 24 hour",
        "liter per second per square second",
        "log (base 10) copies per milliliter",
        "log (base 10) international unit",
        "log (base 10) international unit per milliliter",
        "log base 10",
        "low power field",
        "lumen",
        "lumen square meter",
        "Lyme index value",
        "Mac Lagan unit",
        "megasecond",
        "microgram per gram of feces",
        "microgram fibrinogen equivalent unit per milliliter",
        "microgram per 100 gram",
        "microgram per cubic meter",
        "microgram per deciliter of red blood cells",
        "microgram per gram of dry tissue",
        "microgram per gram of dry weight",
        "microgram per gram of hair",
        "microgram per gram of hemoglobin",
        "microgram per gram of tissue",
        "microgram per liter of red blood cells",
        "microgram per milliliter class",
        "microgram per milliliter equivalent",
        "microgram per millimole of creatinine",
        "microgram per specimen",
        "microgram per square foot (international)",
        "micromole bone collagen equivalent per mole",
        "micromole per 2 hour",
        "micromole per 8 hour",
        "micromole per deciliter of glomerular filtrate",
        "micromole per kilogram of feces",
        "micromole per liter of red blood cells",
        "micromole per micromole of creatinine",
        "micromole per milligram of creatinine",
        "micromole per millimole of creatinine",
        "micromole per minute per gram of mucosa",
        "milli enzyme unit per millimole of creatinine",
        "milli enzyme unit per gram of hemoglobin",
        "milli enzyme unit per gram of protein",
        "milli enzyme unit per milligram of creatinine",
        "millibar per liter per second",
        "milliequivalent per gram of creatinine",
        "milliequivalent per specimen",
        "milliequivalent per total volume",
        "milligram fibrinogen equivalent unit per liter",
        "milligram per 6 hour",
        "milligram per collection",
        "milligram per day per 1.73 square meter",
        "milligram per deciliter of red blood cells",
        "milligram per gram of dry tissue",
        "milligram per gram of feces",
        "milligram per gram of tissue",
        "milligram per gram of wet tissue",
        "milligram per kilogram per 8 hour",
        "milligram per kilogram per hour",
        "milligram per liter of red blood cells",
        "milligram per milligram of creatinine",
        "milligram per specimen",
        "milligram per total output",
        "milligram per total volume",
        "milliliter of fetal red blood cells",
        "milliliter per 5 hour",
        "milliliter per 6 hour",
        "milliliter per heart beat",
        "milliliter per heart beat per square meter",
        "millimole per 5 hour",
        "millimole per ejaculate",
        "millimole per kilogram per 8 hour",
        "millimole per liter of red blood cells",
        "millimole per millimole of urea",
        "millimole per millmole of creatinine",
        "millimole per specimen",
        "millimole per total volume",
        "million colony forming unit per liter",
        "million international unit",
        "million per 24 hour",
        "millipascal second",
        "minidrop per minute",
        "minidrop per second",
        "molecule per platelet",
        "month-day-year",
        "mutation",
        "nanoenzyme unit per milliliter",
        "nanoenzyme unit per red blood cell",
        "nanogram fibrinogen equivalent unit per milliliter",
        "nanogram per enzyme unit",
        "nanogram per milligram of creatinine",
        "nanogram per milligram of protein",
        "nanogram per milliliter of red blood cells",
        "nanogram per million red blood cells",
        "nanomole bone collagen equivalent",
        "nanomole bone collagen equivalent per liter",
        "nanomole bone collagen equivalent per millimole of creatinine",
        "nanomole of 1/2 cystine per milligram of protein",
        "nanomole of ATP",
        "nanomole per deciliter of glomerular filtrate",
        "nanomole per milligram of creatinine",
        "nanomole per milligram of protein",
        "nanomole per milligram of protein per hour",
        "nanomole per minute",
        "nanomole per minute per milligram of hemoglobin",
        "nanomole per minute per million cells",
        "number per high power field",
        "number per liter",
        "number per low power field",
        "number per microliter",
        "number per milliliter",
        "number per minute",
        "Ohm meter",
        "osmole",
        "panbio unit",
        "per 10 thousand red blood cells",
        "per cubic meter",
        "per entity",
        "per gram of hemoglobin",
        "per gram of total nitrogen",
        "per gram of total protein",
        "per gram of wet tissue",
        "per international unit",
        "per kilogram of body weight",
        "per millimeter",
        "per millimole of creatinine",
        "per oil immersion field",
        "per thousand",
        "per thousand red blood cells",
        "per trillion red blood cells",
        "percent loss of acetylcholine receptor",
        "percent penetration",
        "percent abnormal",
        "percent activity",
        "percent aggregation",
        "percent at 60 minute",
        "percent basal activity",
        "percent binding",
        "percent blockade",
        "percent blocked",
        "percent bound",
        "percent breakdown",
        "percent deficient",
        "percent dose",
        "percent excretion",
        "percent hemoglobin",
        "percent hemolysis",
        "percent index",
        "percent inhibition",
        "percent loss",
        "percent lysis",
        "percent normal",
        "percent normal pooled plasma",
        "percent of bacteria",
        "percent of baseline",
        "percent of cells",
        "percent of red blood cells",
        "percent of white blood cells",
        "percent positive",
        "percent reactive",
        "percent recovery",
        "percent reference",
        "percent residual",
        "percent saturation",
        "percent total",
        "percent uptake",
        "percent viable",
        "percentile",
        "phenotype",
        "picoampere",
        "picogram per cell",
        "picogram per milligram of creatinine",
        "picogram per red blood cell",
        "picomole per 24 hour",
        "picomole per red blood cell",
        "pint",
        "relative percent",
        "relative saturation",
        "rubella virus",
        "saturation",
        "second per control",
        "Siemens",
        "Sievert",
        "signal to cutoff ratio",
        "standard deviation",
        "Tesla",
        "thousand copies per milliliter",
        "thousand red blood cells",
        "thyroid-stimulating immunoglobulin index",
        "Weber",
        "white blood cells",
        "1*",
        "minute",
        "second",
        "percent of slope",
        "PercentBound",
        "Per100Spermatozoa",
        "PerGramHemoglobin",
        "acre",
        "acre",
        "Amb a 1 units",
        "barrel",
        "board foot",
        "British thermal unit",
        "British thermal unit at 39 °F",
        "British thermal unit at 59 °F",
        "British thermal unit at 60 °F",
        "international table British thermal unit",
        "mean British thermal unit",
        "thermochemical British thermal unit",
        "bushel",
        "bushel",
        "velocity of light",
        "nutrition label Calories",
        "carat of gold alloys",
        "metric carat",
        "CELL CULTURE INFECTIOUS DOSE 50%",
        "cubic foot",
        "Gunter's chain",
        "Gunter's chain Surveyor's chain",
        "cicero Didot's pica",
        "circular mil",
        "cord",
        "cord",
        "cubic yard",
        "D-ANTIGEN UNITS",
        "didot Didot's point",
        "diopter",
        "dry pint",
        "dry quart",
        "dram drachm",
        "Dye unit",
        "elementary charge",
        "permittivity of vacuum",
        "fluid dram",
        "FOCUS-FORMING UNITS",
        "foot",
        "foot",
        "fathom",
        "fathom",
        "furlong",
        "Newtonian constant of gravitation",
        "historical winchester gallon",
        "gill",
        "gill",
        "Planck constant",
        "hand",
        "Hounsfield unit",
        "horsepower",
        "HOMEOPATHIC POTENCY OF CENTESIMAL SERIES",
        "HOMEOPATHIC POTENCY OF MILLESIMAL SERIES",
        "HOMEOPATHIC POTENCY OF QUINTAMILLESIMAL SERIES",
        "HOMEOPATHIC POTENCY OF DECIMAL SERIES",
        "inch",
        "inch of mercury column",
        "inch",
        "InternationalUnitsPerDeciLiter",
        "InternationalUnitsPerGram",
        "InternationalUnitsPerKilogram",
        "InternationalUnitsPerLiter",
        "InternationalUnitsPerMilliLiter",
        "Boltzmann constant",
        "knot",
        "knot",
        "Kunkel unit",
        "pound",
        "pound",
        "pound force",
        "long hunderdweight British hundredweight",
        "LIMIT OF FLOCCULATION",
        "ligne French line",
        "link for Gunter's chain",
        "link for Gunter's chain",
        "line",
        "long ton British ton",
        "light-year",
        "electron mass",
        "proton mass",
        "mesh",
        "metabolic equivalent",
        "mile",
        "mil",
        "mil",
        "minim",
        "permeability of vacuum",
        "nautical mile",
        "ounce (US and British)",
        "pace",
        "pica",
        "Printer's pica",
        "prism diopter",
        "PLAQUE-FORMING UNITS",
        "the number pi",
        "pied French foot",
        "peck",
        "peck",
        "point",
        "Printer's point",
        "PROTEIN NITROGEN UNITS",
        "pouce French inch",
        "peripheral vascular resistance unit",
        "pennyweight",
        "Ramden's chain Engineer's chain",
        "rod",
        "rod",
        "link for Ramden's chain",
        "Svedberg unit",
        "scruple",
        "section",
        "short hundredweight U.S. hundredweight",
        "Somogyi unit",
        "square mile",
        "Smoot",
        "square rod",
        "stone British stone",
        "TISSUE CULTURE INFECTIOUS DOSE 50%",
        "township",
        "UNITED STATES PHARMACOPEIA UNIT",
        "yard",
        "yard",
        "CellsPerMicroLiter",
        "CopiesPerMilliLiter",
        "crossing threshold",
        "EhrlichUnitsPerDeciLiter",
        "EhrlichUnitsPerDeciLiter [Arbitrary Concentration Units]",
        "ElisaUnitsPerMilliLiter",
        "ElisaUnitsPerMilliLiter [Arbitrary Concentration Units]",
        "HOMEOPATHIC POTENCY OF CENTESIMAL KORSAKOVIAN SERIES",
        "red blood cell count",
        "SpermatozoaPerMilliLiter",
        "tablets",
        "particles total count",
        "the number ten for arbitrary powers",
        "the number ten for arbitrary powers",
        "mean Gregorian year",
        "mean Julian year",
        "tropical year",
        "Ångström",
        "are",
        "astronomic unit",
        "barn",
        "bel",
        "bel kilowatt",
        "bel millivolt",
        "bel sound pressure",
        "bel microvolt",
        "bel volt",
        "bel watt",
        "baud",
        "Biot",
        "bit",
        "bit",
        "byte",
        "Coulomb",
        "calorie at 15 °C",
        "calorie at 20 °C",
        "international table calorie",
        "mean calorie",
        "thermochemical calorie",
        "candela",
        "CURIE",
        "circle",
        "dyne",
        "Gauss",
        "gram percent",
        "gram meter per heartbeat",
        "Gal",
        "Gilbert",
        "gram-force",
        "gon grade",
        "KiloInternationalUnitsPerMilliLiter",
        "kilogram of wet tissue",
        "Kayser",
        "Lambert",
        "lux",
        "meter of water column",
        "meter of mercury column",
        "MilliGramPerTotalVolume",
        "MilligramsPerMilligramCreatinine",
        "milligram of creatinine",
        "mho",
        "MilliMolesPerTotalVolume [Substance Units]",
        "MilliMolesPerMoleCreatinine",
        "mean Gregorian month",
        "mean Julian month",
        "synodal month",
        "Maxwell",
        "neper",
        "Oersted",
        "Poise",
        "parsec",
        "phot",
        "Roentgen",
        "radian",
        "radiation absorbed dose",
        "radiation equivalent man",
        "stilb",
        "spere",
        "steradian",
        "stere",
        "unified atomic mass unit",
        "MICROCURIE",
        "Watt",
    ]


class IMDVersion:
    IMD_YEARS = [2015, 2019]
