from functools import partial
from typing import List, Dict

from pyspark.sql.functions import to_date

from dsp.dam.conversions import dt_to_yyyyMMdd_dashed, to_array_from_comma_separated_str, to_comma_separated_str, \
    to_int, to_str, to_tinyint, to_decimal, to_bigint, to_timestamp_from_string
from dsp.datasets.common import Fields as CommonFields
from dsp.datasets.cquin.output import Fields as CQUINOut
from dsp.outputs.dids.output import Fields as DIDSOut
from dsp.datasets.pcaremeds import DECIMAL_PRECISION
from dsp.common.structured_model import META
from dsp.shared.constants import DS

CQUIN_TYPE_COERCIONS = [
    (CQUINOut.ELIGIBLE_ORGS, to_array_from_comma_separated_str, to_comma_separated_str)
]

DIDS_TYPE_COERCIONS = [
    (DIDSOut.DATE_OF_BIRTH, to_date, dt_to_yyyyMMdd_dashed),
    (DIDSOut.DIAGNOSTIC_TEST_DATE, to_date, dt_to_yyyyMMdd_dashed),
    (DIDSOut.DIAGNOSTIC_TEST_REQUEST_DATE, to_date, dt_to_yyyyMMdd_dashed),
    (DIDSOut.DIAGNOSTIC_TEST_REQUEST_RECEIVED_DATE, to_date, dt_to_yyyyMMdd_dashed),
    (DIDSOut.SERVICE_REPORT_ISSUE_DATE, to_date, dt_to_yyyyMMdd_dashed),
    (DIDSOut.GENDER_CODE, to_tinyint, to_str),
    (DIDSOut.NHS_NUMBER_SUPPLIED, to_int, to_str),
    (DIDSOut.YEAR_OF_TEST, to_int, to_str),
    (DIDSOut.MONTH_OF_TEST, to_int, to_str),
    (DIDSOut.TEST_REQUEST_TO_TEST_REQUEST_RECEIVED, to_int, to_str),
    (DIDSOut.TEST_REQUEST_TO_TEST, to_int, to_str),
    (DIDSOut.TEST_REQUEST_TO_SERVICE_REPORT_ISSUED, to_int, to_str),
    (DIDSOut.TEST_REQUEST_RECEIVED_TO_TEST, to_int, to_str),
    (DIDSOut.TEST_REQUEST_RECEIVED_TO_SERVICE_REPORT_ISSUED, to_int, to_str),
    (DIDSOut.TEST_TO_SERVICE_REPORT_ISSUED, to_int, to_str),
    (DIDSOut.MIGRATION_DATE, to_timestamp_from_string, to_str),
    (DIDSOut.SUBMISSION_DATA_ID, to_bigint, to_str),
]

expected_type_coercions = {
    DS.CQUIN: CQUIN_TYPE_COERCIONS,
    DS.DIDS: DIDS_TYPE_COERCIONS,
}

ignored_columns = {
    DS.CSDS_GENERIC: [
        CommonFields.META,
        "UniqueID_CYP001",
        "RecordNumber"
    ],
    DS.CSDS_V1_6: [
        CommonFields.META,
        "UniqueID_CYP001",
        "RecordNumber",
        "FileCreation_DateTime"
    ],
    DS.CQUIN: [
        CommonFields.META,
    ],
    DS.DEID: [
        CommonFields.META,
    ],
    DS.DIDS: [
        CommonFields.META,
        "MPSConfidence"
    ],
    DS.IAPT_GENERIC: [
        CommonFields.META,
        "UniqueID_IDS101"
    ],
    DS.IAPT_V2_1: [
        CommonFields.META,
        "UniqueID_IDS101"
    ],
    DS.MHSDS_GENERIC: [
        CommonFields.META,
        "MHS101UniqID",
        "UniqSubmissionID",
        "RecordNumber"
    ],
    DS.MHSDS_V1_TO_V5_AS_V6: [
        CommonFields.META,
        "MHS101UniqID",
        "UniqSubmissionID",
        "RecordNumber"
    ],
    DS.MSDS: [
        CommonFields.META,
        "RowNumber",
        "MSD101_ID",
        "UniqSubmissionID",
        "RecordNumber"
    ],
    DS.PCAREMEDS: [
        CommonFields.META,
    ],
    DS.EPMAWSPC: [
        CommonFields.META,
    ],
    DS.EPMAWSAD: [
        CommonFields.META,
    ],
    DS.EPMAWSPC2: [
        CommonFields.META,
    ],
    DS.EPMAWSAD2: [
        CommonFields.META,
    ],
    DS.EPMANATIONALADM: [
        CommonFields.META,
    ],
    DS.EPMANATIONALPRES: [
        CommonFields.META,
    ],
}

ignored_column_values = {
    DS.CQUIN: [],
    DS.DIDS: [],
}  # type: Dict[str, List[str]]

ignored_nested_columns = {
    DS.CSDS_GENERIC: [
        "RecordNumber",
        "UniqueID_CYP000",
        "UniqueID_CYP002",
        "UniqueID_CYP003",
        "UniqueID_CYP004",
        "UniqueID_CYP005",
        "UniqueID_CYP006",
        "UniqueID_CYP007",
        "UniqueID_CYP101",
        "UniqueID_CYP102",
        "UniqueID_CYP103",
        "UniqueID_CYP104",
        "UniqueID_CYP105",
        "UniqueID_CYP201",
        "UniqueID_CYP202",
        "UniqueID_CYP301",
        "UniqueID_CYP401",
        "UniqueID_CYP402",
        "UniqueID_CYP403",
        "UniqueID_CYP404",
        "UniqueID_CYP501",
        "UniqueID_CYP502",
        "UniqueID_CYP601",
        "UniqueID_CYP602",
        "UniqueID_CYP603",
        "UniqueID_CYP604",
        "UniqueID_CYP605",
        "UniqueID_CYP606",
        "UniqueID_CYP607",
        "UniqueID_CYP608",
        "UniqueID_CYP609",
        "UniqueID_CYP610",
        "UniqueID_CYP611",
        "UniqueID_CYP612",
        "UniqueID_CYP613",
        "UniqueID_CYP901",
        "UniqueSubmissionID",
    ],
    DS.CSDS_V1_6: [
        "RecordNumber",
        "UniqueID_CYP000",
        "UniqueID_CYP002",
        "UniqueID_CYP003",
        "UniqueID_CYP004",
        "UniqueID_CYP005",
        "UniqueID_CYP006",
        "UniqueID_CYP007",
        "UniqueID_CYP008",
        "UniqueID_CYP101",
        "UniqueID_CYP102",
        "UniqueID_CYP103",
        "UniqueID_CYP104",
        "UniqueID_CYP105",
        "UniqueID_CYP201",
        "UniqueID_CYP202",
        "UniqueID_CYP301",
        "UniqueID_CYP401",
        "UniqueID_CYP402",
        "UniqueID_CYP403",
        "UniqueID_CYP404",
        "UniqueID_CYP501",
        "UniqueID_CYP502",
        "UniqueID_CYP601",
        "UniqueID_CYP602",
        "UniqueID_CYP603",
        "UniqueID_CYP604",
        "UniqueID_CYP605",
        "UniqueID_CYP606",
        "UniqueID_CYP607",
        "UniqueID_CYP608",
        "UniqueID_CYP609",
        "UniqueID_CYP610",
        "UniqueID_CYP611",
        "UniqueID_CYP612",
        "UniqueID_CYP613",
        "UniqueID_CYP901",
        "UniqueSubmissionID",
        "ReferralRequest_ReceivedTime",
        "Contact_Time",
        "FileCreation_DateTime"
    ],
    DS.IAPT_GENERIC: [
        "RecordNumber",
        "UniqueID_IDS000",
        "UniqueID_IDS001",
        "UniqueID_IDS002",
        "UniqueID_IDS004",
        "UniqueID_IDS007",
        "UniqueID_IDS011",
        "UniqueID_IDS012",
        "UniqueID_IDS101",
        "UniqueID_IDS105",
        "UniqueID_IDS108",
        "UniqueID_IDS201",
        "UniqueID_IDS202",
        "UniqueID_IDS205",
        "UniqueID_IDS602",
        "UniqueID_IDS603",
        "UniqueID_IDS606",
        "UniqueID_IDS607",
        "UniqueID_IDS803",
        "UniqueSubmissionID"
    ],
    DS.IAPT_V2_1: [
        "RecordNumber",
        "UniqueID_IDS000",
        "UniqueID_IDS001",
        "UniqueID_IDS002",
        "UniqueID_IDS003",
        "UniqueID_IDS004",
        "UniqueID_IDS007",
        "UniqueID_IDS011",
        "UniqueID_IDS012",
        "UniqueID_IDS101",
        "UniqueID_IDS105",
        "UniqueID_IDS108",
        "UniqueID_IDS201",
        "UniqueID_IDS202",
        "UniqueID_IDS205",
        "UniqueID_IDS601",
        "UniqueID_IDS602",
        "UniqueID_IDS603",
        "UniqueID_IDS606",
        "UniqueID_IDS607",
        "UniqueID_IDS803",
        "UniqueSubmissionID"
    ],
    DS.MHSDS_GENERIC: [
        "RecordNumber",
        "UniqSubmissionID",
        "MHS000UniqID",
        "MHS501UniqID",
        "MHS502UniqID",
        "MHS505UniqID",
        "MHS513UniqID",
        "MHS506UniqID",
        "MHS507UniqID",
        "MHS514UniqID",
        "MHS509UniqID",
        "MHS510UniqID",
        "MHS511UniqID",
        "MHS503UniqID",
        "MHS504UniqID",
        "MHS512UniqID",
        "MHS603UniqID",
        "MHS604UniqID",
        "MHS605UniqID",
        "MHS606UniqID",
        "MHS102UniqID",
        "MHS103UniqID",
        "MHS104UniqID",
        "MHS105UniqID",
        "MHS106UniqID",
        "MHS107UniqID",
        "MHS204UniqID",
        "MHS201UniqID",
        "MHS202UniqID",
        "MHS607UniqID",
        "MHS203UniqID",
        "MHS001UniqID",
        "MHS804UniqID",
        "MHS801UniqID",
        "MHS802UniqID",
        "MHS004UniqID",
        "MHS003UniqID",
        "MHS002UniqID",
        "MHS005UniqID",
        "MHS006UniqID",
        "MHS007UniqID",
        "MHS010UniqID",
        "MHS011UniqID",
        "MHS012UniqID",
        "MHS008UniqID",
        "MHS009UniqID",
        "MHS601UniqID",
        "MHS701UniqID",
        "MHS702UniqID",
        "MHS401UniqID",
        "MHS402UniqID",
        "MHS403UniqID",
        "MHS404UniqID",
        "MHS405UniqID",
        "MHS803UniqID"
    ],
    DS.MHSDS_V1_TO_V5_AS_V6: [
        "RecordNumber",
        "UniqSubmissionID",
        "MHS000UniqID",
        "MHS501UniqID",
        "MHS502UniqID",
        "MHS505UniqID",
        "MHS515UniqID",
        "MHS516UniqID",
        "MHS517UniqID",
        "MHS513UniqID",
        "MHS506UniqID",
        "MHS507UniqID",
        "MHS514UniqID",
        "MHS509UniqID",
        "MHS510UniqID",
        "MHS511UniqID",
        "MHS503UniqID",
        "MHS504UniqID",
        "MHS512UniqID",
        "MHS603UniqID",
        "MHS604UniqID",
        "MHS605UniqID",
        "MHS606UniqID",
        "MHS102UniqID",
        "MHS103UniqID",
        "MHS104UniqID",
        "MHS105UniqID",
        "MHS106UniqID",
        "MHS107UniqID",
        "MHS204UniqID",
        "MHS201UniqID",
        "MHS202UniqID",
        "MHS607UniqID",
        "MHS203UniqID",
        "MHS001UniqID",
        "MHS804UniqID",
        "MHS801UniqID",
        "MHS802UniqID",
        "MHS004UniqID",
        "MHS003UniqID",
        "MHS002UniqID",
        "MHS005UniqID",
        "MHS006UniqID",
        "MHS007UniqID",
        "MHS010UniqID",
        "MHS011UniqID",
        "MHS012UniqID",
        "MHS013UniqID",
        "MHS008UniqID",
        "MHS009UniqID",
        "MHS601UniqID",
        "MHS701UniqID",
        "MHS702UniqID",
        "MHS401UniqID",
        "MHS402UniqID",
        "MHS403UniqID",
        "MHS404UniqID",
        "MHS405UniqID",
        "MHS803UniqID"
    ],
    DS.MSDS: [
        "RowNumber",
        "MSD000_ID",
        "MSD001_ID",
        "MSD002_ID",
        "MSD003_ID",
        "MSD004_ID",
        "MSD101_ID",
        "MSD102_ID",
        "MSD103_ID",
        "MSD104_ID",
        "MSD105_ID",
        "MSD106_ID",
        "MSD107_ID",
        "MSD108_ID",
        "MSD109_ID",
        "MSD201_ID",
        "MSD202_ID",
        "MSD203_ID",
        "MSD301_ID",
        "MSD302_ID",
        "MSD401_ID",
        "MSD402_ID",
        "MSD403_ID",
        "MSD404_ID",
        "MSD405_ID",
        "MSD406_ID",
        "MSD501_ID",
        "MSD502_ID",
        "MSD503_ID",
        "MSD504_ID",
        "MSD601_ID",
        "MSD602_ID",
        "MSD901_ID",
        "UniqSubmissionID",
        "RecordNumber"
    ]
}
