####################################################################################
#                                   -----                                        #
#  THIS FILE IS AUTOMATICALLY GENERATED BY dsp.datasets.fields.create_fields.py  #
#                      BEWARE ALL YEA WHO EDIT IT MANUALLY                      #
#                                   -----                                        #
##################################################################################

CANONICAL_NAMES = {
    'ACTION': 'ACTION',
    'ATTRIBUTE': 'ATTRIBUTE',
    'CODE': 'CODE',
    'DATASET': 'DATASET',
    'DQ_TS': 'DQ_TS',
    'FIELDS': 'FIELDS',
    'FIELD_VALUES': 'FIELD_VALUES',
    'MESSAGE': 'MESSAGE',
    'ROW_INDEX': 'ROW_INDEX',
    'SUBMISSION_ID': 'SUBMISSION_ID',
    'TABLE': 'TABLE',
    'TYPE': 'TYPE'
}

CANONICAL_NAMES_REV = {v: k for k, v in CANONICAL_NAMES.items()}


class Fields:
    SUBMISSION_ID = 'SUBMISSION_ID'
    DATASET = 'DATASET'
    TABLE = 'TABLE'
    ROW_INDEX = 'ROW_INDEX'
    ATTRIBUTE = 'ATTRIBUTE'
    FIELDS = 'FIELDS'
    CODE = 'CODE'
    MESSAGE = 'MESSAGE'
    FIELD_VALUES = 'FIELD_VALUES'
    TYPE = 'TYPE'
    ACTION = 'ACTION'
    DQ_TS = 'DQ_TS'


Order = [
    Fields.SUBMISSION_ID,
    Fields.DATASET,
    Fields.TABLE,
    Fields.ROW_INDEX,
    Fields.ATTRIBUTE,
    Fields.FIELDS,
    Fields.CODE,
    Fields.MESSAGE,
    Fields.FIELD_VALUES,
    Fields.TYPE,
    Fields.ACTION,
    Fields.DQ_TS,
]
