# pylint: disable=line-too-long,too-many-lines
from pyspark.sql.functions import months_between, floor, col, lit

from dsp.common.regex_patterns import POSTCODE_PATTERN
from dsp.datasets.common import Fields as Common
from dsp.datasets.definitions.iapt.submission_constants import *
from dsp.datasets.definitions.iapt.submission_constants import Metadata
from dsp.datasets.validations.common import DateDelta, ISO639_1_LANG_CODES
from dsp.datasets.validations.iapt.validation_functions import is_valid_assessment_scale_code_rule, \
    uniqueness_rule_iapt_carecontact, is_valid_time_column_rule, is_valid_datetime_column_rule, \
    is_valid_assessment_scale_score_rule, is_valid_score_format_for_snomed_code, \
    iapt_date_before_or_on_date_rule, iapt_date_on_or_after_date_rule
from dsp.validation.common_validation_functions import (
    MAX_PERSON_AGE,
    is_valid_record,
    is_valid_date_column_rule,
    date_before_specified_date,
    values_are_equal_rule,
    onset_date_is_after_birth_date_rule,
    is_valid_gp_practice_code_or_null_rule,
    is_valid_postcode_or_null_rule,
    is_valid_site_id_or_null_rule,
    is_valid_organisation_identifier_or_null_ignoring_succession_rule,
    is_valid_find_code_rule,
    is_valid_snomed_ct_rule,
    uniqueness_with_condition_rule,
    column_not_blank_with_condition_rule,
    column_not_in_format_rule,
    referential_integrity_rule,
    column_value_valid_nhs_number_rule,
    uniqueness_rule,
    column_value_in_set_rule,
    column_is_numeric_rule,
    column_is_alphanumeric_rule,
    column_format_rule,
    column_not_blank_rule,
    placeholder_rule,
    column_comparison_rule
)
from shared.constants import DS


DATAFRAME_VALIDATIONS = [
    # Placeholder validations
    placeholder_rule(
        "IDSREJ001",
        "IDS000Header", "Failed database structure check. Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    placeholder_rule(
        "IDSREJ002", "IDS000Header", "Header Table is empty. Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    placeholder_rule(
        "IDSREJ003",
        "IDS001MPI",
        "Failed Content Check. MPI Table is empty. Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    placeholder_rule(
        "IDSREJ004",
        "IDS101Referral",
        "Failed Content Check. Service or Team Referral table is empty. \
        Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    placeholder_rule(
        "IDSREJ005",
        "IDS002GP",
        "Failed Content Check. GP Practice Registration table is empty. \
        Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    placeholder_rule("IDS00223", "IDS002GP", "An End Date (GMP Patient Registration) has been \
                                                            submitted but there is no corresponding record with a \
                                                            consecutive Start Date (GMP Patient Registration). \
                                                            Implemented in dsp/datasets/pipelines/iapt/__init__.py"),
    column_not_blank_rule('IDS00001', 'IDS000Header', IDS000['DatSetVer'].qualified_name),
    column_value_in_set_rule('IDS00003', 'IDS000Header', IDS000['DatSetVer'].qualified_name, {'2.0'}),
    column_format_rule('IDS00004', 'IDS000Header', IDS000['DatSetVer'].qualified_name,
                                      r"^[0-9]{1,2}\.[0-9]{1,2}$"),
    column_not_blank_rule('IDS00028', 'IDS000Header', IDS000['OrgIDProv'].qualified_name),
    column_is_alphanumeric_rule('IDS00029', 'IDS000Header', IDS000['OrgIDProv'].qualified_name, min_len=3,
                                max_len=6),
    column_not_blank_rule('IDS00031', 'IDS000Header', IDS000['OrgIDSubmit'].qualified_name),
    column_is_alphanumeric_rule('IDS00032', 'IDS000Header', IDS000['OrgIDSubmit'].qualified_name, min_len=3,
                                max_len=6),
    column_not_blank_rule('IDS00012', 'IDS000Header', IDS000['PrimSystemInUse'].qualified_name),
    column_is_alphanumeric_rule('IDS00013', 'IDS000Header', IDS000['PrimSystemInUse'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS00014', 'IDS000Header', IDS000['ReportingPeriodStartDate'].qualified_name),
    column_not_blank_rule('IDS00017', 'IDS000Header', IDS000['ReportingPeriodEndDate'].qualified_name),
    column_not_blank_rule('IDS00020', 'IDS000Header', IDS000['DateTimeDatSetCreate'].qualified_name),
    column_not_blank_rule('IDS00101', 'IDS001MPI', IDS001['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS00102', 'IDS001MPI', IDS001['LocalPatientId'].qualified_name, min_len=0,
                                max_len=20),
    column_not_blank_rule('IDS00151', 'IDS001MPI', IDS001['OrgIDLocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS00152', 'IDS001MPI', IDS001['OrgIDLocalPatientId'].qualified_name,
                                min_len=3, max_len=5),
    column_is_alphanumeric_rule('IDS00155', 'IDS001MPI', IDS001['OrgIDResidenceResp'].qualified_name,
                                min_len=3, max_len=5),
    column_not_blank_rule('IDS00111', 'IDS001MPI', IDS001['NHSNumber'].qualified_name),
    column_is_alphanumeric_rule('IDS00115', 'IDS001MPI', IDS001['NHSNumberStatus'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS00116', 'IDS001MPI', IDS001['NHSNumberStatus'].qualified_name,
                                            {'01', '02', '06', '03', '07', '05', '04'}),
    column_comparison_rule(
        code='IDS00118',
        target_field=IDS001['NHSNumberStatus'],
        compare_fields=(IDS001['NHSNumber'],),
        comparison_operator=lambda nhs_number_status,
                                   nhs_number: nhs_number.isNotNull() | nhs_number_status.isNotNull(),
        header_table=IDS000),
    column_not_blank_rule('IDS00162', 'IDS001MPI', IDS001['NHSNumberStatus'].qualified_name),
    column_not_blank_rule('IDS00120', 'IDS001MPI', IDS001['PersonBirthDate'].qualified_name),
    column_not_blank_rule('IDS00123', 'IDS001MPI', IDS001['Postcode'].qualified_name),
    column_not_blank_rule('IDS00129', 'IDS001MPI', IDS001['Gender'].qualified_name),
    column_is_alphanumeric_rule('IDS00130', 'IDS001MPI', IDS001['Gender'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00131', 'IDS001MPI', IDS001['Gender'].qualified_name,
                                            {'2', 'X', '1', '9'}),
    column_is_alphanumeric_rule('IDS00132', 'IDS001MPI', IDS001['EthnicCategory'].qualified_name, min_len=0,
                                max_len=2),
    column_value_in_set_rule('IDS00133', 'IDS001MPI',
                                            IDS001['EthnicCategory'].qualified_name,
                                            {'S', 'B', 'D', 'G', 'A', 'H', 'K', 'E',
                                             'F', 'L', 'C', 'M', 'N', 'R', 'Z', 'P', '99', 'J'}),
    column_is_alphanumeric_rule('IDS00159', 'IDS001MPI', IDS001['ExBAFIndicator'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS00160', 'IDS001MPI', IDS001['ExBAFIndicator'].qualified_name,
                                            {'UU', '02', 'ZZ', '03', '05'}),
    column_is_alphanumeric_rule('IDS00138', 'IDS001MPI', IDS001['LanguageCodePreferred'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS00139', 'IDS001MPI', IDS001['LanguageCodePreferred'].qualified_name,
                                            ISO639_1_LANG_CODES.union({'q3', 'q1', 'q2', 'q5', 'q4'})),
    column_is_alphanumeric_rule('IDS00157', 'IDS001MPI', IDS001['EduEstabTypeIAPT'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00158', 'IDS001MPI', IDS001['EduEstabTypeIAPT'].qualified_name,
                                            {'3', '4', 'X', 'Z', '1', '2', '8'}),
    column_not_blank_rule('IDS00201', 'IDS002GP', IDS002['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS00202', 'IDS002GP', IDS002['LocalPatientId'].qualified_name, min_len=0,
                                max_len=20),
    column_not_blank_rule('IDS00203', 'IDS002GP', IDS002['GMPCodeReg'].qualified_name),
    column_is_alphanumeric_rule('IDS00204', 'IDS002GP', IDS002['GMPCodeReg'].qualified_name, min_len=6,
                                max_len=6),

    column_not_blank_rule('IDS00217', 'IDS002GP', IDS002['OrgIDGPPrac'].qualified_name),
    column_is_alphanumeric_rule('IDS00218', 'IDS002GP', IDS002['OrgIDGPPrac'].qualified_name, min_len=3,
                                max_len=5),
    column_not_blank_rule('IDS00403', 'IDS004EmpStatus', IDS004['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS00404', 'IDS004EmpStatus', IDS004['LocalPatientId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS00405', 'IDS004EmpStatus', IDS004['EmployStatus'].qualified_name),
    column_is_alphanumeric_rule('IDS00406', 'IDS004EmpStatus', IDS004['EmployStatus'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS00407', 'IDS004EmpStatus', IDS004['EmployStatus'].qualified_name,
                                            {'01', '02', 'ZZ', '06', '03', '07', '05', '04', '08'}),
    column_not_blank_rule('IDS00412', 'IDS004EmpStatus', IDS004['EmployStatusRecDate'].qualified_name),
    column_is_alphanumeric_rule('IDS00410', 'IDS004EmpStatus', IDS004['WeekHoursWorked'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS00411', 'IDS004EmpStatus', IDS004['WeekHoursWorked'].qualified_name,
                                            {'01', '02', '03', '98', '97', '04', '99'}),
    column_is_alphanumeric_rule('IDS00413', 'IDS004EmpStatus', IDS004['SelfEmployInd'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS00414', 'IDS004EmpStatus', IDS004['SelfEmployInd'].qualified_name,
                                            {'X', 'N', 'Z', 'Y', '8'}),
    column_is_alphanumeric_rule('IDS00415', 'IDS004EmpStatus', IDS004['SickAbsenceInd'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS00416', 'IDS004EmpStatus', IDS004['SickAbsenceInd'].qualified_name,
                                            {'X', 'N', 'Z', 'Y', '8'}),
    column_is_alphanumeric_rule('IDS00417', 'IDS004EmpStatus', IDS004['SSPInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00418', 'IDS004EmpStatus', IDS004['SSPInd'].qualified_name,
                                            {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS00421', 'IDS004EmpStatus', IDS004['JSAInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00422', 'IDS004EmpStatus', IDS004['JSAInd'].qualified_name,
                                            {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS00423', 'IDS004EmpStatus', IDS004['ESAInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00424', 'IDS004EmpStatus', IDS004['ESAInd'].qualified_name,
                                            {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS00425', 'IDS004EmpStatus', IDS004['UCInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00426', 'IDS004EmpStatus', IDS004['UCInd'].qualified_name,
                                            {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS00427', 'IDS004EmpStatus', IDS004['PIPInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS00428', 'IDS004EmpStatus', IDS004['PIPInd'].qualified_name,
                                            {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS00431', 'IDS004EmpStatus', IDS004['EmpSupportInd'].qualified_name,
                                min_len=0, max_len=2),
    column_value_in_set_rule('IDS00432', 'IDS004EmpStatus', IDS004['EmpSupportInd'].qualified_name,
                                            {'N', 'Y', 'NA'}),
    column_not_blank_rule('IDS00703', 'IDS007DisabilityType', IDS007['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS00704', 'IDS007DisabilityType', IDS007['LocalPatientId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS00705', 'IDS007DisabilityType', IDS007['DisabCode'].qualified_name),
    column_is_alphanumeric_rule('IDS00706', 'IDS007DisabilityType', IDS007['DisabCode'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS00707', 'IDS007DisabilityType', IDS007['DisabCode'].qualified_name,
                                            {'01', '02', 'ZZ', '06', '03', '07', '10', '05', 'XX', 'NN', '04', '08',
                                             '09'}),
    column_not_blank_rule('IDS01103', 'IDS011SocPerCircumstances',
                                         IDS011['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS01104', 'IDS011SocPerCircumstances',
                                IDS011['LocalPatientId'].qualified_name, min_len=0,
                                max_len=20),
    column_not_blank_rule('IDS01108', 'IDS011SocPerCircumstances',
                                         IDS011['SocPerCircumstance'].qualified_name),
    is_valid_snomed_ct_rule('IDS01109', 'IDS011SocPerCircumstances', 'SocPerCircumstance', min_length=6,
                            max_length=18),
    column_not_blank_rule('IDS01110', 'IDS011SocPerCircumstances',
                                         IDS011['SocPerCircumstanceRecDate'].qualified_name),
    column_not_blank_rule('IDS01203', 'IDS012OverseasVisitorChargCat',
                                         IDS012['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS01204', 'IDS012OverseasVisitorChargCat',
                                IDS012['LocalPatientId'].qualified_name, min_len=0,
                                max_len=20),
    column_not_blank_rule('IDS01205', 'IDS012OverseasVisitorChargCat',
                                         IDS012['OvsVisChCat'].qualified_name),
    column_is_alphanumeric_rule('IDS01206', 'IDS012OverseasVisitorChargCat', 'OvsVisChCat', min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS01207', 'IDS012OverseasVisitorChargCat',
                                            IDS012['OvsVisChCat'].qualified_name,
                                            {'B', 'D', 'A', 'E', '9', 'F', 'C', 'P'}),
    column_not_blank_rule('IDS01210', 'IDS012OverseasVisitorChargCat',
                                         IDS012['OvsVisChCatAppDate'].qualified_name),
    column_not_blank_rule('IDS10104', 'IDS101Referral', IDS101['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS10105', 'IDS101Referral',
                                IDS101['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS10106', 'IDS101Referral', IDS101['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS10107', 'IDS101Referral', IDS101['LocalPatientId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS10108', 'IDS101Referral', IDS101['OrgIDComm'].qualified_name),
    column_is_alphanumeric_rule('IDS10109', 'IDS101Referral',
                                IDS101['OrgIDComm'].qualified_name, min_len=3, max_len=5),
    column_not_blank_rule('IDS10111', 'IDS101Referral',
                                         IDS101['ReferralRequestReceivedDate'].qualified_name),
    column_is_alphanumeric_rule('IDS10117', 'IDS101Referral', IDS101['SourceOfReferralMH'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS10118', 'IDS101Referral', IDS101['SourceOfReferralMH'].qualified_name,
                                            {'E3', 'F1', 'M3', 'M6', 'E1', 'E4', 'E2', 'G4', 'N2', 'D1', 'M7', 'A1',
                                             'H2', 'G1', 'G2', 'C1', 'E6', 'F3', 'I2', 'A2', 'N1', 'P1', 'G3', 'A4',
                                             'B1', 'M1', 'D2', 'E5', 'B2', 'C2', 'I1', 'H1', 'M2', 'M5', 'A3', 'M4',
                                             'M8', 'C3', 'F2'}),
    column_format_rule('IDS10132', 'IDS101Referral', IDS101['OnsetDate'].qualified_name,
                                      r"^[0-9]{4}(-|/)([0][1-9]|[1][0,1,2])$"),
    column_not_in_format_rule('IDS10142', 'IDS101Referral', IDS101['OnsetDate'].qualified_name,
                                             r"^[0-9]{4}/([0][1-9]|[1][0,1,2])$"),
    column_is_alphanumeric_rule('IDS10133', 'IDS101Referral', IDS101['PrevDiagCondInd'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS10134', 'IDS101Referral',
                                            IDS101['PrevDiagCondInd'].qualified_name, {'U', 'N', 'Y', 'Z'}),
    column_is_alphanumeric_rule('IDS10135', 'IDS101Referral', IDS101['EndCode'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS10136', 'IDS101Referral', IDS101['EndCode'].qualified_name,
                                            {'11', '10', '13', '95', '17', '96', '12', '50', '47', '46', '14', '49',
                                             '48', '16'}),

    column_not_blank_rule('IDS10501', 'IDS105OnwardReferral', IDS105['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS10502', 'IDS105OnwardReferral', IDS105['ServiceRequestId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS10503', 'IDS105OnwardReferral', IDS105['OnwardReferDate'].qualified_name),

    column_is_alphanumeric_rule('IDS10506', 'IDS105OnwardReferral',
                                IDS105['OnwardReferReason'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS10507', 'IDS105OnwardReferral',
                                            IDS105['OnwardReferReason'].qualified_name,
                                            {'01', '02', '06', '03', '98', '05', '04', '96', '99'}),
    column_is_alphanumeric_rule('IDS10518', 'IDS105OnwardReferral', IDS105['OrgIDReceiving'].qualified_name,
                                min_len=3, max_len=5),
    column_not_blank_rule('IDS10803', 'IDS108WaitingTimePauses', IDS108['PauseID'].qualified_name),
    column_is_alphanumeric_rule('IDS10804', 'IDS108WaitingTimePauses', IDS108['PauseID'].qualified_name,
                                min_len=0, max_len=5),
    column_not_blank_rule('IDS10805', 'IDS108WaitingTimePauses',
                                         IDS108['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS10806', 'IDS108WaitingTimePauses',
                                IDS108['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS10807', 'IDS108WaitingTimePauses',
                                         IDS108['PauseStartDate'].qualified_name),

    column_is_alphanumeric_rule('IDS10814', 'IDS108WaitingTimePauses', IDS108['PauseReason'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS10815', 'IDS108WaitingTimePauses', IDS108['PauseReason'].qualified_name,
                                            {'01', '02', '03'}),
    column_not_blank_rule('IDS10817', 'IDS108WaitingTimePauses', IDS108['PauseReason'].qualified_name),
    column_not_blank_rule('IDS20101', 'IDS201CareContact', IDS201['CareContactId'].qualified_name),
    column_is_alphanumeric_rule('IDS20102', 'IDS201CareContact', IDS201['CareContactId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS20103', 'IDS201CareContact', IDS201['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS20104', 'IDS201CareContact', IDS201['ServiceRequestId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS20106', 'IDS201CareContact', IDS201['CareContDate'].qualified_name),
    column_is_alphanumeric_rule('IDS20146', 'IDS201CareContact', IDS201['OrgIDComm'].qualified_name,
                                min_len=3, max_len=5),  # TODO how to generate with qualified name?
    column_is_alphanumeric_rule('IDS20150', 'IDS201CareContact',
                                IDS201['PlannedCareContIndicator'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS20151', 'IDS201CareContact',
                                            IDS201['PlannedCareContIndicator'].qualified_name, {'N', 'Y'}),
    column_is_alphanumeric_rule('IDS20127', 'IDS201CareContact', IDS201['AttendOrDNACode'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS20128', 'IDS201CareContact', IDS201['AttendOrDNACode'].qualified_name,
                                            {'3', '5', '4', '6', '7', '2'}),
    column_is_alphanumeric_rule('IDS20152', 'IDS201CareContact', IDS201['Cancellation'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS20153', 'IDS201CareContact', IDS201['Cancellation'].qualified_name,
                                            {'N', 'Y'}),
    column_is_numeric_rule('IDS20114', 'IDS201CareContact', 'ClinContDurOfCareCont', min_len=0, max_len=4),
    column_not_blank_rule('IDS20115', 'IDS201CareContact', IDS201['IAPTLTCServiceInd'].qualified_name),
    column_is_alphanumeric_rule('IDS20116', 'IDS201CareContact', IDS201['IAPTLTCServiceInd'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS20117', 'IDS201CareContact', IDS201['IAPTLTCServiceInd'].qualified_name,
                                            {'Y', 'N'}),
    column_not_blank_rule('IDS20154', 'IDS201CareContact', IDS201['AppType'].qualified_name),
    column_is_alphanumeric_rule('IDS20155', 'IDS201CareContact', IDS201['AppType'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS20156', 'IDS201CareContact', IDS201['AppType'].qualified_name,
                                            {'01', '02', '03', '04', '05', '06', '07', '08'}),
    column_is_alphanumeric_rule('IDS20119', 'IDS201CareContact', IDS201['ConsMediumUsed'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS20120', 'IDS201CareContact', IDS201['ConsMediumUsed'].qualified_name,
                                            {'01', '02', '06', '03', '98', '05', '04', '08'}),
    column_is_alphanumeric_rule('IDS20157', 'IDS201CareContact', IDS201['IntEnabledTherProg'].qualified_name,
                                min_len=0, max_len=20),
    column_is_alphanumeric_rule('IDS20125', 'IDS201CareContact',
                                IDS201['CareContPatientTherMode'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS20126', 'IDS201CareContact',
                                            IDS201['CareContPatientTherMode'].qualified_name,
                                            {'2', '1', '3'}),
    column_is_numeric_rule('IDS20158', 'IDS201CareContact', IDS201['NumGroupTherParticipants'].qualified_name,
                           min_len=0, max_len=3),
    column_is_numeric_rule('IDS20159', 'IDS201CareContact', IDS201['NumGroupTherFacilitators'].qualified_name,
                           min_len=0, max_len=2),
    column_is_alphanumeric_rule('IDS20160', 'IDS201CareContact', IDS201['PsychMed'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS20161', 'IDS201CareContact', IDS201['PsychMed'].qualified_name,
                                            {'01', '02', 'UU', 'ZZ', '03'}),
    column_is_alphanumeric_rule('IDS20121', 'IDS201CareContact', IDS201['ActLocTypeCode'].qualified_name,
                                min_len=3, max_len=3),
    column_value_in_set_rule('IDS20122', 'IDS201CareContact', IDS201['ActLocTypeCode'].qualified_name,
                                            {'D02', 'D03', 'G02', 'G04', 'L03', 'G03', 'H01', 'E01', 'D01', 'N02',
                                             'N05', 'L06', 'L05', 'E03', 'L01', 'M06', 'K02', 'A03', 'A01', 'M05',
                                             'C01', 'A02', 'A04', 'M01', 'E02', 'L02', 'M07', 'L99', 'B02', 'J01',
                                             'M02', 'N01', 'F01', 'K01', 'N03', 'L04', 'B01', 'E04', 'M03', 'M04',
                                             'C02', 'G01', 'X01', 'N04', 'E99', 'C03'}),
    column_is_alphanumeric_rule('IDS20148', 'IDS201CareContact', IDS201['SiteIDOfTreat'].qualified_name,
                                min_len=5, max_len=9),
    column_is_alphanumeric_rule('IDS20162', 'IDS201CareContact', IDS201['LanguageCodeTreat'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS20163', 'IDS201CareContact', IDS201['LanguageCodeTreat'].qualified_name,
                                            ISO639_1_LANG_CODES.union({'q3', 'q1', 'q2', 'q5', 'q4'})),
    column_is_alphanumeric_rule('IDS20164', 'IDS201CareContact',
                                IDS201['InterpreterPresentInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS20165', 'IDS201CareContact',
                                            IDS201['InterpreterPresentInd'].qualified_name,
                                            {'3', '5', '4', 'X', '1', '2'}),
    column_not_blank_rule('IDS20201', 'IDS202CareActivity', IDS202['CareActId'].qualified_name),
    column_is_alphanumeric_rule('IDS20202', 'IDS202CareActivity', IDS202['CareActId'].qualified_name,
                                min_len=0, max_len=20),
    column_not_blank_rule('IDS20203', 'IDS202CareActivity', IDS202['CareContactId'].qualified_name),
    column_is_alphanumeric_rule('IDS20204', 'IDS202CareActivity', IDS202['CareContactId'].qualified_name,
                                min_len=0, max_len=20),
    column_is_alphanumeric_rule('IDS20205', 'IDS202CareActivity', IDS202['CarePersLocalId'].qualified_name,
                                min_len=0, max_len=20),
    column_is_numeric_rule('IDS20206', 'IDS202CareActivity', IDS202['ClinContactDurOfCareAct'].qualified_name,
                           min_len=0, max_len=4),
    column_is_alphanumeric_rule('IDS20212', 'IDS202CareActivity', IDS202['FindSchemeInUse'].qualified_name,
                                min_len=2, max_len=2),
    column_value_in_set_rule('IDS20213', 'IDS202CareActivity', IDS202['FindSchemeInUse'].qualified_name,
                                            {'01', '04'}),
    column_is_alphanumeric_rule('IDS20215', 'IDS202CareActivity', IDS202['CodeFind'].qualified_name,
                                min_len=4, max_len=18),
    column_is_alphanumeric_rule('IDS20222', 'IDS202CareActivity', IDS202['ObsValue'].qualified_name,
                                min_len=0, max_len=10),
    column_is_alphanumeric_rule('IDS20223', 'IDS202CareActivity', IDS202['UnitMeasure'].qualified_name,
                                min_len=0, max_len=10),
    is_valid_snomed_ct_rule('IDS20230', 'IDS202CareActivity',
                            IDS202['CodeProcAndProcStatus'].qualified_name, max_length=56),
    is_valid_snomed_ct_rule('IDS20231', 'IDS202CareActivity', IDS202['CodeObs'].qualified_name),
    column_not_blank_rule('IDS20502', 'IDS205InternetTherLog',
                                         IDS205['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS20503', 'IDS205InternetTherLog',
                                IDS205['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS20504', 'IDS205InternetTherLog',
                                         IDS205['StartDateIntEnabledTherLog'].qualified_name),
    column_not_blank_rule('IDS20507', 'IDS205InternetTherLog',
                                         IDS205['EndDateIntEnabledTherLog'].qualified_name),
    column_not_blank_rule('IDS20512', 'IDS205InternetTherLog',
                                         IDS205['IntEnabledTherProg'].qualified_name),
    column_is_alphanumeric_rule('IDS20513', 'IDS205InternetTherLog',
                                IDS205['IntEnabledTherProg'].qualified_name, min_len=0,
                                max_len=20),
    column_not_blank_rule('IDS20514', 'IDS205InternetTherLog',
                                         IDS205['DurationIntEnabledTher'].qualified_name),
    column_is_numeric_rule('IDS20515', 'IDS205InternetTherLog',
                           IDS205['DurationIntEnabledTher'].qualified_name, min_len=0,
                           max_len=4),
    column_is_alphanumeric_rule('IDS20516', 'IDS205InternetTherLog', IDS205['CarePersLocalId'].qualified_name,
                                min_len=0,
                                max_len=20),
    column_is_alphanumeric_rule('IDS20517', 'IDS205InternetTherLog',
                                IDS205['IntegratedSoftwareInd'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS20518', 'IDS205InternetTherLog',
                                            IDS205['IntegratedSoftwareInd'].qualified_name, {'Y', 'N'}),
    column_not_blank_rule('IDS60202', 'IDS602LongTermCondition',
                                         IDS602['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS60203', 'IDS602LongTermCondition',
                                IDS602['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS60204', 'IDS602LongTermCondition',
                                         IDS602['FindSchemeInUse'].qualified_name),
    column_is_alphanumeric_rule('IDS60205', 'IDS602LongTermCondition',
                                IDS602['FindSchemeInUse'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS60206', 'IDS602LongTermCondition',
                                            IDS602['FindSchemeInUse'].qualified_name, {'01', '04'}),
    column_not_blank_rule('IDS60207', 'IDS602LongTermCondition',
                                         IDS602['LongTermCondition'].qualified_name),
    column_is_alphanumeric_rule('IDS60208', 'IDS602LongTermCondition',
                                IDS602['LongTermCondition'].qualified_name, min_len=4,
                                max_len=18),
    column_not_blank_rule('IDS60303', 'IDS603PresentingComplaints',
                                         IDS603['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS60304', 'IDS603PresentingComplaints',
                                IDS603['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS60305', 'IDS603PresentingComplaints',
                                         IDS603['FindSchemeInUse'].qualified_name),
    column_is_alphanumeric_rule('IDS60306', 'IDS603PresentingComplaints',
                                IDS603['FindSchemeInUse'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS60307', 'IDS603PresentingComplaints',
                                            IDS603['FindSchemeInUse'].qualified_name, {'01', '04'}),
    column_not_blank_rule('IDS60308', 'IDS603PresentingComplaints', IDS603['PresComp'].qualified_name),
    column_is_alphanumeric_rule('IDS60309', 'IDS603PresentingComplaints', IDS603['PresComp'].qualified_name,
                                min_len=4, max_len=18),
    column_is_alphanumeric_rule('IDS60311', 'IDS603PresentingComplaints',
                                IDS603['PresCompCodSig'].qualified_name, min_len=1,
                                max_len=1),
    column_value_in_set_rule('IDS60312', 'IDS603PresentingComplaints',
                                            IDS603['PresCompCodSig'].qualified_name, {'2', '1'}),
    column_not_blank_rule('IDS60315', 'IDS603PresentingComplaints',
                                         IDS603['PresCompCodSig'].qualified_name),
    column_not_blank_rule('IDS60601', 'IDS606CodedScoreAssessmentRefer',
                                         IDS606['ServiceRequestId'].qualified_name),
    column_is_alphanumeric_rule('IDS60602', 'IDS606CodedScoreAssessmentRefer',
                                IDS606['ServiceRequestId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS60603', 'IDS606CodedScoreAssessmentRefer',
                                         IDS606['CodedAssToolType'].qualified_name),
    column_is_numeric_rule('IDS60604', 'IDS606CodedScoreAssessmentRefer',
                           IDS606['CodedAssToolType'].qualified_name, min_len=6,
                           max_len=18),
    column_not_blank_rule('IDS60605', 'IDS606CodedScoreAssessmentRefer',
                                         IDS606['PersScore'].qualified_name),
    column_is_alphanumeric_rule('IDS60606', 'IDS606CodedScoreAssessmentRefer',
                                IDS606['PersScore'].qualified_name, min_len=0,
                                max_len=5),
    column_not_blank_rule('IDS60608', 'IDS606CodedScoreAssessmentRefer',
                                         IDS606['AssToolCompDate'].qualified_name),
    column_not_blank_rule('IDS60701', 'IDS607CodedScoreAssessmentAct',
                                         IDS607['CareActId'].qualified_name),
    column_is_alphanumeric_rule('IDS60702', 'IDS607CodedScoreAssessmentAct',
                                IDS607['CareActId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS60703', 'IDS607CodedScoreAssessmentAct',
                                         IDS607['CodedAssToolType'].qualified_name),
    column_is_numeric_rule('IDS60704', 'IDS607CodedScoreAssessmentAct',
                           IDS607['CodedAssToolType'].qualified_name, min_len=6,
                           max_len=18),
    column_not_blank_rule('IDS60705', 'IDS607CodedScoreAssessmentAct',
                                         IDS607['PersScore'].qualified_name),
    column_is_alphanumeric_rule('IDS60706', 'IDS607CodedScoreAssessmentAct',
                                IDS607['PersScore'].qualified_name, min_len=0,
                                max_len=5),
    column_not_blank_rule('IDS80302', 'IDS803CareCluster', IDS803['LocalPatientId'].qualified_name),
    column_is_alphanumeric_rule('IDS80303', 'IDS803CareCluster', IDS803['LocalPatientId'].qualified_name,
                                min_len=0, max_len=20),
    column_is_alphanumeric_rule('IDS80308', 'IDS803CareCluster',
                                IDS803['AMHCareClustCodeFin'].qualified_name, min_len=2, max_len=2),
    column_not_blank_rule('IDS80321', 'IDS803CareCluster', IDS803['AMHCareClustCodeFin'].qualified_name),
    column_value_in_set_rule('IDS80309', 'IDS803CareCluster',
                                            IDS803['AMHCareClustCodeFin'].qualified_name,
                                            {'02', '11', '06', '21', '03', '12', '19', '15', '09', '16', '10', '04',
                                             '08', '17', '00', '13', '01', '20', '07', '05', '18', '14'}),
    column_not_blank_rule('IDS80304', 'IDS803CareCluster', IDS803['StartDateCareClust'].qualified_name),

    column_not_blank_rule('IDS90201', 'IDS902CarePersQual', IDS902['CarePersLocalId'].qualified_name),
    column_is_alphanumeric_rule('IDS90202', 'IDS902CarePersQual',
                                IDS902['CarePersLocalId'].qualified_name, min_len=0, max_len=20),
    column_not_blank_rule('IDS90203', 'IDS902CarePersQual',
                                         IDS902['QualAttainLevelIAPT'].qualified_name),
    column_is_alphanumeric_rule('IDS90204', 'IDS902CarePersQual',
                                IDS902['QualAttainLevelIAPT'].qualified_name, min_len=2,
                                max_len=2),
    column_value_in_set_rule('IDS90205', 'IDS902CarePersQual',
                                            IDS902['QualAttainLevelIAPT'].qualified_name,
                                            {'11', '30', '16', '17', '12', '10', '13', '15', '31', '14'}),

    # custom validations
    # values are equal
    values_are_equal_rule('IDS00016', IDS000['ReportingPeriodStartDate'], Metadata['ReportingPeriodStart'], DS.IAPT),
    values_are_equal_rule('IDS00019', IDS000['ReportingPeriodEndDate'], Metadata['ReportingPeriodEnd'], DS.IAPT),
    values_are_equal_rule('IDS00030', IDS000['OrgIDProv'], Metadata['ProviderId'], DS.IAPT),
    values_are_equal_rule('IDS00033', IDS000['OrgIDSubmit'], Metadata['SenderId'], DS.IAPT),
    # date before , after in between
    iapt_date_before_or_on_date_rule('IDS00027', IDS000['DateTimeDatSetCreate'], Metadata['SubmittedTimestamp']),
    iapt_date_before_or_on_date_rule(
        'IDS10113', IDS101['ReferralRequestReceivedDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS10128', IDS101['ServDischDate'], IDS101['ReferralRequestReceivedDate']),
    iapt_date_before_or_on_date_rule('IDS10139', IDS101['ServDischDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule(
        'IDS20108', IDS201['CareContDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule('IDS60610', IDS606['AssToolCompDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule('IDS00436', IDS004['EmployStatusRecDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule('IDS01107', IDS011['SocPerCircumstanceRecDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule('IDS01209', IDS012['OvsVisChCatAppDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_before_or_on_date_rule('IDS10505', IDS105['OnwardReferDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS10521', IDS105['OnwardReferDate'], IDS101['ReferralRequestReceivedDate']),
    iapt_date_on_or_after_date_rule('IDS10522', IDS105['OnwardReferDate'], IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS10809', IDS108['PauseStartDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS10816', IDS108['PauseStartDate'], IDS101['ReferralRequestReceivedDate']),
    iapt_date_on_or_after_date_rule('IDS10811', IDS108['PauseEndDate'], IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS10812', IDS108['PauseEndDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS10813', IDS108['PauseEndDate'], IDS108['PauseStartDate']),
    iapt_date_on_or_after_date_rule('IDS20170', IDS201['CareContDate'], IDS000['ReportingPeriodStartDate']),
    iapt_date_on_or_after_date_rule('IDS20171', IDS201['CareContDate'], IDS101['ReferralRequestReceivedDate']),
    iapt_date_before_or_on_date_rule('IDS20506', IDS205['StartDateIntEnabledTherLog'],
                                     IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS20520', IDS205['StartDateIntEnabledTherLog'],
                                    IDS101['ReferralRequestReceivedDate']),
    iapt_date_on_or_after_date_rule('IDS20509', IDS205['EndDateIntEnabledTherLog'], IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS20510', IDS205['EndDateIntEnabledTherLog'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS20511', IDS205['EndDateIntEnabledTherLog'],
                                    IDS205['StartDateIntEnabledTherLog']),
    iapt_date_before_or_on_date_rule('IDS60314', IDS603['PresCompDate'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS60618', IDS606['AssToolCompDate'], IDS000['ReportingPeriodStartDate']),
    iapt_date_on_or_after_date_rule('IDS60617', IDS606['AssToolCompDate'], IDS101['ReferralRequestReceivedDate']),
    iapt_date_before_or_on_date_rule('IDS80306', IDS803['StartDateCareClust'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS80315', IDS803['EndDateCareClust'], IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS80316', IDS803['EndDateCareClust'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS80317', IDS803['EndDateCareClust'], IDS803['StartDateCareClust']),
    iapt_date_before_or_on_date_rule('IDS90207', IDS902['QualAwardedDate'], IDS000['ReportingPeriodEndDate']),
    date_before_specified_date(
        'IDS90212', IDS902.name, IDS902['QualAwardedDate'].qualified_name, '2005-01-01'),
    iapt_date_on_or_after_date_rule('IDS90213', IDS902['QualAwardedDate'], IDS902['QualPlannedCompletionDate']),
    iapt_date_on_or_after_date_rule('IDS90209', IDS902['QualPlannedCompletionDate'],
                                    IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS90215', IDS902['QualPlannedCompletionDate'], IDS000['ReportingPeriodEndDate'],
                                     offset=DateDelta(years=2)),
    column_not_blank_with_condition_rule(
        'IDS90214', IDS902.name,
        IDS902['QualAwardedDate'].qualified_name,
        ('QualPlannedCompletionDate',),
        lambda qual_planned_completion_date: qual_planned_completion_date.isNull()),
    iapt_date_before_or_on_date_rule('IDS00211', IDS002['StartDateGMPRegistration'], IDS000['ReportingPeriodEndDate'],
                                     offset=DateDelta(days=1)),
    iapt_date_on_or_after_date_rule('IDS00214', IDS002['EndDateGMPRegistration'], IDS000['ReportingPeriodStartDate']),
    iapt_date_before_or_on_date_rule('IDS00215', IDS002['EndDateGMPRegistration'], IDS000['ReportingPeriodEndDate']),
    iapt_date_on_or_after_date_rule('IDS00216', IDS002['EndDateGMPRegistration'], IDS002['StartDateGMPRegistration']),
    iapt_date_on_or_after_date_rule('IDS00212', IDS002['StartDateGMPRegistration'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS00438', IDS004['EmployStatusRecDate'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS00439', IDS004['EmpSupportReferral'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS10140', IDS101['ReferralRequestReceivedDate'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS01111', IDS011['SocPerCircumstanceRecDate'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS01211', IDS012['OvsVisChCatAppDate'], IDS001['PersonBirthDate']),
    iapt_date_on_or_after_date_rule('IDS60316', IDS603['PresCompDate'], IDS001['PersonBirthDate']),
    iapt_date_before_or_on_date_rule('IDS00437', IDS004['EmpSupportReferral'], IDS000['ReportingPeriodEndDate']),

    # file level rejects
    column_value_valid_nhs_number_rule('IDSREJ006', 'IDS001MPI', "NHSNumber"),
    column_format_rule('IDSREJ007', 'IDS001MPI', "Postcode", POSTCODE_PATTERN),
    uniqueness_rule('IDSREJ009', 'IDS001MPI', {'NHSNumber'}),
    uniqueness_rule('IDSREJ010', 'IDS001MPI', {'LocalPatientId'}),
    placeholder_rule(
        'IDSREJ012', 'AllTables',
        'Invalid Dates Validation. Implemented in dsp/datasets/pipelines/iapt.py ApplyIDSREJ012ValidationStage'),
    placeholder_rule('IDSREJ015', 'IDS000Header',
                                    "Invalid Header Table Validation. Implemented in dsp/datasets/pipelines/iapt.py"),
    placeholder_rule('IDSREJ101', 'IDS101Referral',
                                    'Invalid Dates Validation. Implemented in dsp/datasets/pipelines/iapt.py'),

    # valid date check
    is_valid_date_column_rule('IDS00015', 'IDS000Header', 'ReportingPeriodStartDate'),
    is_valid_date_column_rule('IDS00018', 'IDS000Header', 'ReportingPeriodEndDate'),
    is_valid_date_column_rule('IDS00210', 'IDS002GP', 'StartDateGMPRegistration'),
    is_valid_date_column_rule('IDS00213', 'IDS002GP', 'EndDateGMPRegistration'),
    is_valid_date_column_rule('IDS00408', 'IDS004EmpStatus', 'EmployStatusRecDate'),
    is_valid_date_column_rule('IDS00434', 'IDS004EmpStatus', 'EmpSupportReferral'),
    is_valid_date_column_rule('IDS01106', 'IDS011SocPerCircumstances', 'SocPerCircumstanceRecDate'),
    is_valid_date_column_rule('IDS01208', 'IDS012OverseasVisitorChargCat', 'OvsVisChCatAppDate'),
    is_valid_date_column_rule('IDS10112', 'IDS101Referral', 'ReferralRequestReceivedDate'),
    is_valid_date_column_rule('IDS10127', 'IDS101Referral', 'ServDischDate'),
    is_valid_date_column_rule('IDS10504', 'IDS105OnwardReferral', 'OnwardReferDate'),
    is_valid_date_column_rule('IDS10808', 'IDS108WaitingTimePauses', 'PauseStartDate'),
    is_valid_date_column_rule('IDS10810', 'IDS108WaitingTimePauses', 'PauseEndDate'),
    is_valid_date_column_rule('IDS20107', 'IDS201CareContact', 'CareContDate'),
    is_valid_date_column_rule('IDS20505', 'IDS205InternetTherLog', 'StartDateIntEnabledTherLog'),
    is_valid_date_column_rule('IDS20508', 'IDS205InternetTherLog', 'EndDateIntEnabledTherLog'),
    is_valid_date_column_rule('IDS60313', 'IDS603PresentingComplaints', 'PresCompDate'),
    is_valid_date_column_rule('IDS60609', 'IDS606CodedScoreAssessmentRefer', 'AssToolCompDate'),
    is_valid_date_column_rule('IDS80305', 'IDS803CareCluster', 'StartDateCareClust'),
    is_valid_date_column_rule('IDS80314', 'IDS803CareCluster', 'EndDateCareClust'),
    is_valid_date_column_rule('IDS90206', 'IDS902CarePersQual', 'QualAwardedDate'),
    is_valid_date_column_rule('IDS90208', 'IDS902CarePersQual', 'QualPlannedCompletionDate'),
    is_valid_time_column_rule(code='IDS60614', table_name='IDS606CodedScoreAssessmentRefer', _='AssToolCompTime'),
    is_valid_time_column_rule(code='IDS10514', table_name='IDS105OnwardReferral', _='OnwardReferTime'),
    is_valid_time_column_rule(code='IDS80307', table_name='IDS803CareCluster', _='StartTimeCareClust'),
    is_valid_time_column_rule(code='IDS80318', table_name='IDS803CareCluster', _='EndTimeCareClust'),
    is_valid_time_column_rule(code='IDS20109', table_name='IDS201CareContact', _='CareContTime'),
    is_valid_datetime_column_rule(code='IDS00021', table_name='IDS000Header', column='DateTimeDatSetCreate'),

    # ref data validations
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS00034", "OrgIDSubmit", IDS000, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS00154", "OrgIDLocalPatientId", IDS001, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS00156", "OrgIDResidenceResp", IDS001, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS10110", IDS101["OrgIDComm"].qualified_name, IDS101, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_postcode_or_null_rule('IDS00125', 'Postcode', IDS001, 'ReportingPeriodStartDate',
                                   IDS000, IDS000),
    is_valid_gp_practice_code_or_null_rule('IDS00206', 'GMPCodeReg', IDS002, 'ReportingPeriodStartDate',
                                           IDS000, IDS000),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS00219", "OrgIDGPPrac", IDS002, "ReportingPeriodStartDate", IDS000, IDS000),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS20147", IDS201["OrgIDComm"].qualified_name, IDS201, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_site_id_or_null_rule(
        "IDS20149", "SiteIDOfTreat", IDS201, "ReportingPeriodStartDate", IDS000, IDS000
    ),
    is_valid_organisation_identifier_or_null_ignoring_succession_rule(
        "IDS10519", "OrgIDReceiving", IDS105, "ReportingPeriodStartDate", IDS000, IDS000
    ),

    # CUSTOM VALIDATIONS - UNIQUENESS RULE

    uniqueness_rule('IDS00221', 'IDS002GP', {
        IDS002["LocalPatientId"].qualified_name,
        IDS002["GMPCodeReg"].qualified_name,
        IDS002["StartDateGMPRegistration"].qualified_name
    }),
    uniqueness_with_condition_rule('IDS00222', 'IDS002GP',
                                   (IDS002["LocalPatientId"].qualified_name,
                                                   IDS002["EndDateGMPRegistration"].qualified_name),
                                   lambda: col(IDS002['EndDateGMPRegistration'].qualified_name).isNull(),
                                   nulls_are_unique=False
                                   ),
    uniqueness_rule('IDS10103', 'IDS101Referral', {IDS101['ServiceRequestId'].qualified_name}),
    uniqueness_rule('IDS20143', 'IDS201CareContact', {
        IDS201['CareContactId'].qualified_name
    }),
    uniqueness_rule('IDS20225', 'IDS202CareActivity', {'CareActId'}),
    uniqueness_rule('IDS60709', 'IDS607CodedScoreAssessmentAct', {
        IDS607['CareActId'].qualified_name,
        IDS607['CodedAssToolType'].qualified_name
    }),
    uniqueness_rule('IDS00402', 'IDS004EmpStatus', {
        IDS004['LocalPatientId'].qualified_name,
        IDS004['EmployStatusRecDate'].qualified_name
    }),

    uniqueness_with_condition_rule('IDS00440', 'IDS004EmpStatus',
                                   (IDS004['LocalPatientId'].qualified_name,
                                                   IDS004['EmployStatusRecDate'].qualified_name),
                                   lambda: col(IDS004['EmployStatusRecDate'].qualified_name).isNull(),
                                   nulls_are_unique=False
                                   ),
    uniqueness_rule('IDS00702', 'IDS007DisabilityType', {
        IDS007["LocalPatientId"].qualified_name,
        "DisabCode"
    }),
    uniqueness_rule('IDS01102', 'IDS011SocPerCircumstances', {
        IDS011['LocalPatientId'].qualified_name,
        'SocPerCircumstanceRecDate',
        'SocPerCircumstance'
    }),
    uniqueness_rule('IDS01202', 'IDS012OverseasVisitorChargCat', {
        IDS012['LocalPatientId'].qualified_name,
        'OvsVisChCat',
        'OvsVisChCatAppDate'
    }),
    uniqueness_rule('IDS10520', 'IDS105OnwardReferral', {
        IDS105['ServiceRequestId'].qualified_name,
        'OnwardReferDate',
        'OnwardReferTime',
        'OnwardReferReason',
        'OrgIDReceiving'
    }),
    uniqueness_rule('IDS10802', 'IDS108WaitingTimePauses', {
        'PauseID',
        IDS108['ServiceRequestId'].qualified_name
    }),
    uniqueness_rule('IDS20519', 'IDS205InternetTherLog', {
        IDS205['ServiceRequestId'].qualified_name,
        'StartDateIntEnabledTherLog',
        'EndDateIntEnabledTherLog',
        'IntEnabledTherProg',
        'DurationIntEnabledTher',
        'CarePersLocalId'}),
    uniqueness_rule('IDS60210', 'IDS602LongTermCondition', {
        IDS602['ServiceRequestId'].qualified_name,
        'LongTermCondition'
    }),
    uniqueness_rule('IDS60302', 'IDS603PresentingComplaints', {
        IDS603['ServiceRequestId'].qualified_name,
        'PresCompDate',
        'PresComp'
    }),
    uniqueness_with_condition_rule('IDS80319', 'IDS803CareCluster', (
        IDS803['LocalPatientId'].qualified_name,
        'EndDateCareClust'
    ), side_condition=lambda: col('EndDateCareClust').isNull(), nulls_are_unique=False),
    uniqueness_rule('IDS90210', 'IDS902CarePersQual', {'CarePersLocalId',
                                                                      'QualAttainLevelIAPT'}),
    uniqueness_rule_iapt_carecontact('IDS20168', 'IDS201CareContact',
                                     (
                                         IDS201['ServiceRequestId'].qualified_name,
                                         'CareContDate',
                                         'CareContTime'
                                     ), 'AttendOrDNACode'),

    uniqueness_rule('IDS80320', 'IDS803CareCluster',
                                   {IDS803["LocalPatientId"].qualified_name,
                                    IDS803["StartDateCareClust"].qualified_name}),

    uniqueness_rule('IDS60616', 'IDS606CodedScoreAssessmentRefer',
                                   {IDS606["ServiceRequestId"].qualified_name,
                                    IDS606["AssToolCompDate"].qualified_name,
                                    IDS606["AssToolCompTime"].qualified_name,
                                    IDS606["CodedAssToolType"].qualified_name
                                    }, nulls_are_unique=False),

    # CUSTOM VALIDATIONS - COLUMN COMPARISON RULE

    column_comparison_rule('IDSREJ008', IDS001['PersonBirthDate'],
                                          (
                                              IDS000['ReportingPeriodStartDate'],
                                              IDS000['ReportingPeriodEndDate']
                                          ),
                                          lambda birth_date, start_date, end_date:
                                          birth_date.isNull() | start_date.isNull() | end_date.isNull() |
                                          (
                                                  (birth_date <= end_date) &
                                                  (floor(months_between(start_date, birth_date) / 12) <= MAX_PERSON_AGE)
                                          ),
                                          header_table=IDS000
                                          ),
    column_comparison_rule('IDS00117', IDS001['NHSNumberStatus'], (IDS001['NHSNumber'],),
                                          lambda nhs_number_status, nhs_number:
                                          nhs_number.isNull()
                                          | nhs_number_status.isNull()
                                          | (nhs_number_status != lit("07")),
                                          header_table=IDS000),
    column_comparison_rule('IDS00153', IDS001['OrgIDLocalPatientId'], (IDS000['OrgIDProv'],),
                                          lambda org_id_lpid, org_id_provider:
                                          org_id_lpid.isNull()
                                          | org_id_provider.isNull()
                                          | (org_id_lpid == org_id_provider),
                                          header_table=IDS000),
    column_comparison_rule(code='IDS00161',
                                          target_field=IDS001['NHSNumberStatus'],
                                          compare_fields=(IDS001['NHSNumber'],),
                                          comparison_operator=lambda nhs_number_status, nhs_number:
                                          (nhs_number.isNotNull()) | nhs_number_status.isNull() |
                                          ~(nhs_number_status.isin({'01', '02'})),
                                          header_table=IDS000),
    column_comparison_rule('IDS00433', IDS004['EmpSupportInd'], (IDS004['EmpSupportReferral'],),
                                          lambda emp_support_ind, emp_support_referral:
                                          emp_support_referral.isNull()
                                          | emp_support_ind.isNotNull(),
                                          header_table=IDS000),
    column_comparison_rule('IDS00435', IDS004['EmpSupportReferral'], (IDS004['EmpSupportInd'],),
                                          lambda emp_support_referral, emp_support_ind:
                                          emp_support_referral.isNotNull()
                                          | emp_support_ind.isNull()
                                          | (emp_support_ind != lit("Y")),
                                          header_table=IDS000),
    column_comparison_rule('IDS10137', IDS101['EndCode'], (IDS101['ServDischDate'],),
                                          lambda end_code, serv_disch_date:
                                          serv_disch_date.isNull()
                                          | end_code.isNotNull(),
                                          header_table=IDS000),
    column_comparison_rule('IDS10138', IDS101['ServDischDate'], (IDS101['EndCode'],),
                                          lambda serv_disch_date, end_code:
                                          end_code.isNull()
                                          | serv_disch_date.isNotNull(),
                                          header_table=IDS000),
    column_comparison_rule('IDS20166', IDS201['AttendOrDNACode'], (IDS201['Cancellation'],),
                                          lambda dna_code, cancellation:
                                          cancellation.isNotNull() |
                                          dna_code.isNull()
                                          | (dna_code != lit("2")),
                                          header_table=IDS000),
    column_comparison_rule('IDS20167', IDS201['AttendOrDNACode'], (IDS201['Cancellation'],),
                                          lambda dna_code, cancellation:
                                          cancellation.isNull() |
                                          dna_code.isNull()
                                          | (dna_code == lit("2")),
                                          header_table=IDS000),
    column_comparison_rule('IDS20214', IDS202['FindSchemeInUse'], (IDS202['CodeFind'],),
                                          lambda scheme, finding:
                                          finding.isNull()
                                          | (scheme.isNotNull() & scheme.isin({'01', '04'})),
                                          header_table=IDS000),
    column_comparison_rule('IDS20216', IDS202['FindSchemeInUse'], (IDS202['CodeFind'],),
                                          lambda scheme, finding:
                                          finding.isNotNull()
                                          | scheme.isNull(),
                                          header_table=IDS000),
    column_comparison_rule('IDS20226', IDS202['UnitMeasure'], (IDS202['ObsValue'],),
                                          lambda unit, obs:
                                          unit.isNotNull()
                                          | obs.isNull(),
                                          header_table=IDS000),

    onset_date_is_after_birth_date_rule('IDS10141', IDS101['OnsetDate'], IDS001['PersonBirthDate']),

    # Valid find code validations
    is_valid_find_code_rule('IDS20228', IDS202['FindSchemeInUse'], IDS202['CodeFind']),
    is_valid_find_code_rule('IDS60209', IDS602['FindSchemeInUse'], IDS602['LongTermCondition']),
    is_valid_find_code_rule('IDS60310', IDS603['FindSchemeInUse'], IDS603['PresComp']),

    # Valid assessment scale code validations
    is_valid_assessment_scale_code_rule('IDS60613', IDS606['CodedAssToolType']),
    is_valid_assessment_scale_code_rule('IDS60710', IDS607['CodedAssToolType']),

    # person score validation
    is_valid_assessment_scale_score_rule(
        code='IDS60607', code_field=IDS606['CodedAssToolType'], score_field=IDS606['PersScore']),
    is_valid_assessment_scale_score_rule(
        code='IDS60707', code_field=IDS607['CodedAssToolType'], score_field=IDS607['PersScore']),
    is_valid_score_format_for_snomed_code(
        code='IDS60615', code_field=IDS606['CodedAssToolType'], score_field=IDS606['PersScore']),
    is_valid_score_format_for_snomed_code(
        code='IDS60711', code_field=IDS607['CodedAssToolType'], score_field=IDS607['PersScore']),

    # Failed Autogen Validations
    column_is_alphanumeric_rule('IDS00419', 'IDS004EmpStatus', IDS004['BenefitRecInd'].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS00420', 'IDS004EmpStatus', IDS004['BenefitRecInd'].qualified_name,
                                            {'Y', 'N', 'U', 'Z'}),
    column_is_alphanumeric_rule("IDS00429", "IDS004EmpStatus", IDS004["OtherBenefitInd"].qualified_name,
                                min_len=1, max_len=1),
    column_value_in_set_rule('IDS00430', 'IDS004EmpStatus', IDS004['OtherBenefitInd'].qualified_name,
                                            {'Y', 'N', 'U', 'Z'})
]

REFERENTIAL_INTEGRITY_VALIDATIONS = [
    referential_integrity_rule("IDS00145", IDS001, IDS002,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS00146", IDS001, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS00220", IDS002, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS10101", IDS101, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS20142", IDS201, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS20224", IDS202, IDS201,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS60612", IDS606, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS60708", IDS607, IDS202,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS00401", IDS004, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS00701", IDS007, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS01101", IDS011, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS01201", IDS012, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS10510", IDS105, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS10801", IDS108, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS20501", IDS205, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS60201", IDS602, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS60301", IDS603, IDS101,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
    referential_integrity_rule("IDS80301", IDS803, IDS001,
                                              conditions=lambda: (is_valid_record(Common.DQ),)),
]
